### ISSUE TITLE
AWSMQTTEncoder Crash unexpectedly

### ISSUE THREAD

**Issue by rohitphogat19** [aws-amplify/aws-sdk-ios#4401] opened 2022-11-14 12:21 UTC
Hi Team,
I faces an unexpected crash. I never faces any such crash earlier. I got this error report from AppStore Connect
What can be the possible reason for it:

Pods used are with version => 2.28.0:
```ruby
pod "AWSMobileClient"
pod "AWSIoT"
```

<img width="1400" alt="Screenshot 2022-11-14 at 5 42 16 PM" src="https://user-images.githubusercontent.com/36146505/201658155-5228ff67-f647-46e2-8349-4d8ddb5dad40.png">

<img width="956" alt="Screenshot 2022-11-14 at 5 49 26 PM" src="https://user-images.githubusercontent.com/36146505/201658350-9b08ea83-efcf-4da1-8596-556cf4309032.png">

**Comment by ruisebas** [comment] 2022-11-14 15:09
Hi @rohitphogat19, thanks for opening this issue.

Do you have any crash logs that you can share? That would help us root cause the issue.

**Comment by rohitphogat19** [comment] 2022-11-14 15:53
@ruisebas Please check these if it helps:

### 12th Novmber Crash

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/36146505/201703617-6ab48e35-f656-462c-9e5f-4d0b8597ffd6.png">

```
Crashed: com.apple.root.default-qos
0  libsystem_kernel.dylib         0x7200 __pthread_kill + 8
1  libsystem_pthread.dylib        0x71ac pthread_kill + 268
2  libsystem_c.dylib              0x20ca0 abort + 180
3  libsystem_malloc.dylib         0x1d548 _malloc_put + 550
4  libsystem_malloc.dylib         0x1d7e0 malloc_zone_error + 100
5  libsystem_malloc.dylib         0x5fc4 free_large + 268
6  CoreFoundation                 0x180d34 cbDestroy + 36
7  CoreFoundation                 0x14d7b0 boundPairCommonFinalize + 28
8  CoreFoundation                 0x7d1e4 __CFStreamDeallocate + 136
9  CoreFoundation                 0x7ed20 _CFRelease + 316
10 AWSIoT                         0x61d54 -[AWSIoTMQTTClient webSocketDidOpen:] + 224
11 AWSIoT                         0x8832c __39-[AWSSRWebSocket _HTTPHeadersDidFinish]_block_invoke + 132
12 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
13 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
14 libdispatch.dylib              0x15b8c _dispatch_root_queue_drain + 684
15 libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
16 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
17 libsystem_pthread.dylib        0xb98 start_wqthread + 8
```

### 14th November Crash

```
Crashed: Thread
0  CoreFoundation                 0xcc88 CFArrayGetCount + 16
1  CoreFoundation                 0x1a22c _CFStreamClose + 264
2  AWSIoT                         0x7bb9c -[AWSMQTTEncoder close] + 132
3  AWSIoT                         0x7fb78 -[AWSMQTTSession error:] + 136
4  AWSIoT                         0x7b6c0 -[AWSMQTTDecoder stream:handleEvent:] + 532
5  CoreFoundation                 0x104120 _signalEventSync + 216
6  CoreFoundation                 0x40d0 _cfstream_shared_signalEventSync + 392
7  CoreFoundation                 0xbb414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
8  CoreFoundation                 0xcc1a0 __CFRunLoopDoSource0 + 208
9  CoreFoundation                 0x5694 __CFRunLoopDoSources0 + 268
10 CoreFoundation                 0xb05c __CFRunLoopRun + 828
11 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
12 Foundation                     0x19464 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
13 AWSIoT                         0x5c9a8 -[AWSIoTMQTTClient openStreams:] + 472
14 Foundation                     0x6943c __NSThread__start__ + 808
15 libsystem_pthread.dylib        0x19ac _pthread_start + 148
16 libsystem_pthread.dylib        0xe68 thread_start + 8
```

**Comment by gadget-man** [comment] 2022-11-16 13:57
I'm seeing similar issues
![Screenshot 2022-11-16 at 13 56 17](https://user-images.githubusercontent.com/24406912/202199532-ae4ca17a-02f0-4bf4-a5fc-16d0ebf021ad.png)
[com.iparcelbox.iparcelbox_issue_baf70627c496587387f9ce4b158b5484_crash_session_9e52b562c7ec40169b3b8631699e27a4_DNE_0_v2_stacktrace.txt](https://github.com/aws-amplify/aws-sdk-ios/files/10022311/com.iparcelbox.iparcelbox_issue_baf70627c496587387f9ce4b158b5484_crash_session_9e52b562c7ec40169b3b8631699e27a4_DNE_0_v2_stacktrace.txt)

**Comment by atierian** [comment] 2022-12-09 22:02
Thanks for the crash logs. All three crash logs (the two from @rohitphogat19 and one from @gadget-man) appear to show subtly different, but likely related crashes.

Have either of you found a way to reliably reproduce the crash? Despite best efforts, I haven't been able reproduce it.

**Comment by atierian** [comment] 2023-01-27 14:47
Following up on this. Are either of you still experiencing this crash and/or have you been able to reproduce the crash locally?

**Comment by gadget-man** [comment] 2023-01-27 16:38
I seem to have fixed it. Having done some close looking at the logs, I identified that there was an issue with disconnect being called by another process at the same time as trying to perform an IoT action - causing the crash.

**Comment by atierian** [comment] 2023-01-27 19:56
Thanks for letting us know. I'm closing this issue, but please comment here again or open a new issue if you experience it again. Thanks!

**Closed by atierian** 2023-01-27 19:56 UTC
Labels: bug, pending-response, iot, not-reproducible, closing soon
