### ISSUE TITLE
AWSMobileClientXCF Swift Package Breaks lldb Debugging

### ISSUE THREAD

**Issue by stuartmcmahon-h3d** [aws-amplify/aws-sdk-ios#3966] opened 2022-01-13 00:04 UTC
**Describe the bug**
When debugging an iOS app linked with AWSMobilClientXCF you cannot 'p' or 'po' the value of variable.

**To Reproduce**
1. Set a breakpoint in an iOS app linked with AWSMobileCilentXCF 2.26.6
2. Try to print the value of a variable using 'p' or 'po'.

**Observed Behavior**
```
(lldb) p someVariable
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/AWSAuthSDK-awjpvqlgobdtszaszohsjogaibvn/Build/Intermediates.noindex/ArchiveIntermediates/AWSMobileClientXCF/IntermediateBuildFilesPath/AWSAuthSDK.build/Release-iphoneos/AWSMobileClientXCF.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/AWSAuthSDK-awjpvqlgobdtszaszohsjogaibvn/Build/Intermediates.noindex/ArchiveIntermediates/AWSMobileClientXCF/IntermediateBuildFilesPath/AWSAuthSDK.build/Release-iphoneos/AWSMobileClientXCF.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

**Expected Behavior**
I would expect the value of 'someVariable' to be printed.

**Potential Fix**
Use the flag `-no-serialize-debugging-options` when compiling your libraries, so that absolute paths are not embedded. See Swift issue:
[Couldn't IRGen expression](https://bugs.swift.org/browse/SR-12783?focusedCommentId=56540&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-56540)

**Environment(please complete the following information):**
AWSMobileClientXCF 2.26.6 - issue may be in other AWS libs too?
Xcode 13.1
lldb-1300.0.32.4
Swift version 5.5.1-dev

**Device Information (please complete the following information):**
 - Device: iPhone or Simulator
 - iOS Version: 14 or 15

**Comment by atierian** [comment] 2022-01-14 20:58
Hi @stuartmcmahon-h3d, thanks for opening this issue.

We were able to reproduce this issue on Xcode 13.1, however it seems to be fixed in Xcode 13.2.1. This fix doesn't appeared to be mentioned in the recent Xcode release notes.

Can you please try using Xcode 13.2.1?

**Comment by stuartmcmahon-h3d** [comment] 2022-01-15 01:50
Thanks @atierian, using Xcode 13.2.1 seems to work! Although if I step into a AWSMobileClient function now I get this warning:

```
AWSMobileClientXCF was compiled with optimization - stepping may behave oddly; variables may not be available.
/Users/stuartmcmahon/Library/Developer/Xcode/DerivedData/{our-app-name}-drsabfnuukkewrgfwqyeixewaqxu/Build/Products/Debug-iphoneos/{our-app-name}.app/Frameworks/AWSMobileClientXCF.framework/AWSMobileClientXCF: Cannot load Swift type information; AST validation error in "AWSMobileClientXCF": The module file format is too old to be used by this version of the debugger.
(lldb) 
```
So it's possible that when you rebuild the frameworks with Xcode 13.2.1 the problem may reappear.

I'm happy for you to close this issue for now though, thanks for the help!

**Comment by atierian** [comment] 2022-01-18 13:32
Happy to hear that, thanks for the update.
I'm closing this issue and have opened this [Feature Request](https://github.com/aws-amplify/aws-sdk-ios/issues/3971) for compiling without optimization in DEBUG.

**Closed** 2022-01-18 13:33 UTC
Labels: build

**Comment by arjavwebexcellis** [comment] 2022-02-07 14:28
@atierian 
I'm having this issue on Xcode 13.2.1 too. I'll try Xcode 13.3 and will update here.

**Comment by stuartmcmahon-h3d** [comment] 2022-02-08 00:30
Yeah, I suspect as long as you use a version of XCode **_later_** than the version the AWS libs were compiled with you should be ok. The AWS debug info files are probably just being ignored/not loaded in that case. See output from above:
```
AST validation error in "AWSMobileClientXCF": The module file format is too old to be used by this version of the debugger.
```

**Comment by igabriels** [comment] 2022-02-21 20:18
This issue is reproducing on 

- Xcode 13.2.1 
- macOS Monterey 
- using Swift package managers

and affecting via dependency the amplify iOS sdk 
I sugest re-opening this issue and investigating further

**Comment by nadimalam** [comment] 2022-02-21 20:38
Ive just wasted hours on this issue thinking it was an Xcode cache issue or something :( 

Is there a fix for this using Xcode 13.2.1? 

This issue should not be closed, it should be reopened and pinned at the top as im sure many people will come across the same issue that I had.

**Comment by igabriels** [comment] 2022-02-21 20:47
I've uncovered this issue through amplify-ios-sdk https://github.com/aws-amplify/amplify-ios/issues/1641 this is that ticket. 1.18.2 amplify seems to work - it's respective aws-sdk-ios version is 2.26.7 - @nadimalam try it out and see but to be clear - I've not used it standalone so take that with a grain of salt 😅

**Comment by nadimalam** [comment] 2022-02-21 21:39
> I've uncovered this issue through amplify-ios-sdk [aws-amplify/amplify-ios#1641](https://github.com/aws-amplify/amplify-ios/issues/1641) this is that ticket. 1.18.2 amplify seems to work - it's respective aws-sdk-ios version is 2.26.7 - @nadimalam try it out and see but to be clear - I've not used it standalone so take that with a grain of salt 😅

thanks mate, that works for now!
