### ISSUE TITLE
AWSMobileClient, Sign in with Apple Sheet shows null as the app name.

### ISSUE THREAD

**Issue by rolisanchez** [aws-amplify/aws-sdk-ios#2330] opened 2020-03-03 14:42 UTC
**Describe the bug**
I'm using Amplify Auth to enable multiple Login providers to my app.  When signing in with Apple, I can finish the sign in successfully and obtain requested user attributes.  

The problem when trying to sign in with a real device, is that when opening the Sign in with Apple Sheet, the app name is showing as "null".  See attached picture below as an example of what I mean. The App Icon shows correctly, being the same from the Project assets.

When trying to do the same on a simulator, since there is no Apple ID logged in on it, it opens a WebView, prompting for the Apple ID. Here there is no AppIcon and the name displayed is the Service ID being set up on developer.apple.com Identifiers.

When using the hosted UI, I can see the Cognito Endpoint as a name, but no AppIcon. (See the hosted UI below). 

When looking about it in the app forums for Sign in with Apple for web (https://forums.developer.apple.com/thread/123054), it seems that this App Icon is derived from the App Store after having launched. Since our app is not yet launched, it displays no app icon.

Is it possible that when getting the app name in the real device, it is trying to get it from the App Store too? And that's why we are getting "null" as an app name? Or am I missing a configuration when performing the Sign In with AWSMobileClient?

**To Reproduce**

1. Follow the following guide to add Sign in with Apple to your Cognito Pool
https://aws.amazon.com/blogs/security/how-to-set-up-sign-in-with-apple-for-amazon-cognito/ 

2. Add Apple Sign in to your Swift Project: (Following https://aws-amplify.github.io/docs/ios/authentication)

`let hostedUIOptions = HostedUIOptions(scopes: ["openid", "email", "profile"], identityProvider: "SignInWithApple")`

`AWSMobileClient.default().showSignIn(navigationController: navController, hostedUIOptions: hostedUIOptions) { (userState, error) in` ..... 

**Which AWS service(s) are affected?**
AWS Amplify
AWS Cognito

**Expected behavior**

I'm expecting the App name to be different than null. Since it's extracting the App Icon from the Assets, I was expecting that the iOS sign in sheet would also extract the app name from there.
 
**Screenshots**

![null_apple](https://user-images.githubusercontent.com/7276421/75783605-ca166200-5d9b-11ea-9872-911a7b25b9a6.JPG)

![simulator](https://user-images.githubusercontent.com/7276421/75784901-e0bdb880-5d9d-11ea-9c50-da4b2f211d56.png)

![hosted_UI](https://user-images.githubusercontent.com/7276421/75784285-f41c5400-5d9c-11ea-976c-d3daeb1da8b6.png)

**Environment(please complete the following information):**
 - SDK Version: 'AWSMobileClient', '~> 2.12.1', 'AWSAuthUI', '~> 2.12.1', 'AWSUserPoolsSignIn', '~> 2.12.1'
 - Dependency Manager: CocoaPods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 11 Pro, iPad Pro 9.7
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators: iPhone 11 Pro Max

**Additional context**
- App is not yet launched

**Comment by lawmicha** [comment] 2020-03-05 15:45
hi @rolisanchez, thanks for reporting the issue and providing the detailed information. We are currently investigating issues with Apple Sign-In and will provide an update regarding this "null
 value when we can.

**Comment by hossamghareeb** [comment] 2020-03-10 11:27
I can confirm that this issue is reproducible. I get the same `null` as app name

**Comment by hossamghareeb** [comment] 2020-03-30 08:13
@lawmicha is there any updates on this?

**Comment by karasahinemre** [comment] 2020-04-17 17:36
Same here.

**Comment by pedromancheno** [comment] 2020-05-05 07:28
> hi @rolisanchez, thanks for reporting the issue and providing the detailed information. We are currently investigating issues with Apple Sign-In and will provide an update regarding this "null
> value when we can.

Hello. How is the investigation going? @lawmicha

**Comment by royjit** [comment] 2020-07-02 18:44
Hi all,

This seems to be not an issue with Amplify. The latest public beta 13.6 of iOS seems to have fixed this issue. I could not reproduce the issue in iOS 13.6 beta.

Similar issue in JS library - https://github.com/aws-amplify/amplify-js/issues/4580

**Comment by royjit** [comment] 2020-07-27 15:08
Could not reproduce this bug in the latest iOS version 13.6. Closing this issue, feel free to reach back if you face any problem.

**Closed by royjit** 2020-07-27 15:08 UTC
Labels: AWSMobileClient, Pending

**Comment by ameedsayeh** [comment] 2021-03-09 14:59
this is still happening in iOS 14, any updates?

**Comment by palpatim** [comment] 2021-03-09 17:26
We've seen some new customer reports of this including yours. Please refer to https://github.com/aws-amplify/amplify-ios/issues/1095 since this issue is pretty old and we'd like to track on the more recent one.
