### ISSUE TITLE
Integration Swift Package Manager

### ISSUE THREAD

**Issue by hdmdmm** [aws-amplify/aws-sdk-ios#1942] opened 2019-09-25 11:50 UTC
**Which AWS Services is the feature request for?**
AWSCognito, AWSDynamoDB, AWSS3

**Is your feature request related to a problem? Please describe.**
XCode 11 has Swift Package Manager. For the moment AWS SDK iOS doesn't support SPM.

**Describe the solution you'd like**
Adjust the actual sources of SDK to SPM.

**Comment by palpatim** [comment] 2019-09-25 13:27
Dupe of #313

**Closed by palpatim** 2019-09-25 13:27 UTC
