### ISSUE TITLE
AWSCognito macOS Catalyst Support

### ISSUE THREAD

**Issue by SNAnyDeviceSoftwareSolutions** [aws-amplify/aws-sdk-ios#1986] opened 2019-10-14 04:23 UTC
**Which AWS Services is the feature request for?**

To support macOS Catalyst

**Describe the solution you'd like**
AWSCore has compilation errors

- /Pods/AWSCore/AWSCore/UICKeyChainStore/AWSUICKeyChainStore.m:1011:9: 'SecAddSharedWebCredential' is unavailable: not available on macCatalyst
- /Pods/AWSCore/AWSCore/UICKeyChainStore/AWSUICKeyChainStore.m:1036:5: 'SecRequestSharedWebCredential' is unavailable: not available on macCatalyst
- /Pods/AWSCore/AWSCore/UICKeyChainStore/AWSUICKeyChainStore.m:1055:67: 'kSecSharedPassword' is unavailable: not available on macCatalyst
- /Pods/AWSCore/AWSCore/UICKeyChainStore/AWSUICKeyChainStore.m:1070:30: 'SecCreateSharedWebCredentialPassword' is unavailable: not available on macCatalyst

**Comment by palpatim** [comment] 2019-10-14 22:56
Duplicate of https://github.com/aws-amplify/aws-sdk-ios/issues/1603

**Closed by palpatim** 2019-10-14 22:56 UTC
