### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by btreglia** [aws-amplify/aws-sdk-ios#3033] opened 2020-09-22 07:02 UTC
**Describe the bug**
All swift files that "import AWSMobileClient" generate the error "Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler"  

My project is using the latest AWS iOS SDK (v 2.16.0). I am using many AWS v2.16 frameworks and AWSMobileClient is the only framework that is generating this error.

The problem I am experiencing is identical to [this closed issue](https://github.com/aws-amplify/aws-sdk-ios/issues/2365), except that issue was for a prior version of swift. 

I was able to fix the issue by recompiling the AWSMobileClient framework from the source code with the setting BUILD_LIBRARIES_FOR_DISTRIBUTION = YES, and using this framework in my project. Not an ideal solution since this will require all users using Xcode 12 to recompile this framework, which is not a trivial exercise. The setting "BUILD_LIBRARIES_FOR_DISTRIBUTION = YES" must be set **in the framework** before it is compiled, not in the project that uses the framework as was suggested by AWS Support. 

**To Reproduce**
1. Create a project in Xcode 12 (using the swift 5.3 compiler).
2. Add AWSMobileClient framework 
3. Add "import AWSMobileClient" to one of the source files.
4. Compile

**Observed Behavior**
Build error: "Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler".

**Expected Behavior**
Projects that Include the AWSMobileClient framework should compile without error, like the other AWS frameworks. 

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient
AWSCore
AWSCognitoIdentityProvider
AWSCognitoIdentityProviderASF
AWSAuthCore
AWSDynamoDB
AWSLambda
AWSUserPoolSignIn

**Screenshots**
<img width="1626" alt="Screen+Shot+2020-09-17+at+9 10 00+AM" src="https://user-images.githubusercontent.com/10679547/93851933-e7dae400-fc65-11ea-9d74-97e2ea4142b3.png">

**Environment(please complete the following information):**
 - SDK Version: 2.16.0
 - Dependency Manager: Frameworks (no package manager)
 - Swift Version : 5.3
 - Xcode Version: 12.0

**Device Information (please complete the following information):**
All devices and simulator

**Comment by ruiguoamz** [comment] 2020-09-22 22:13
Hi, @btreglia 
Thanks for reaching out.

I can sometimes see the error. But in my laptop, when I do `Cmd+Shift+K` to clean the project and `Cmd+B/Cmd+R` to rebuild/rerun it, the error will just go away. Could you try it? Thanks

**Comment by ray-liu-imeasureu** [comment] 2020-09-22 22:58
@ruiguoamz I have the exact same issue with @btreglia . Cleaning the build will not work. @btreglia has pointed out the fix. Just need to set BUILD_LIBRARIES_FOR_DISTRIBUTION = YES for the framework project setting and rebuild the framework.

**Comment by btreglia** [comment] 2020-09-22 22:59
> Hi, @btreglia
> Thanks for reaching out.
> 
> I can sometimes see the error. But in my laptop, when I do `Cmd+Shift+K` to clean the project and `Cmd+B/Cmd+R` to rebuild/rerun it, the error will just go away. Could you try it? Thanks

Hi @ruiguoamz, 

I replaced the recompiled version of the AWSMobileClient framework that I created and replaced it with the original AWSMobileClient framework from the v2.16.0 zip and tried the clean/rebuild that you suggested and the error did not go away. I even deleted the DerivedDate folder but still received the same error. 

Thanks.

**Comment by palpatim** [comment] 2020-09-29 21:01
We'll investigate setting the `BUILD_LIBRARIES_FOR_DISTRIBUTION` flag to see if that fixes the issue--that didn't work previously because of a bug in Xcode.

**Comment by EdGonzalez-** [comment] 2020-10-09 17:02
Hi @palpatim, any news on this?

**Comment by palpatim** [comment] 2020-11-06 23:50
To the best of my ability to discern, the underlying Xcode issue has not yet been fixed. When I set the `BUILD_LIBRARIES_FOR_DISTRIBUTION` flag and attempt to import a binary framework built on Xcode 11.4.1/Swift 5.2 into a project, and build that project with Xcode 12/Swift 5.3, I still see the circular reference errors that are the hallmark of the known Swift issue, which has not yet been resolved:

- First mentioned in Xcode release notes: https://developer.apple.com/documentation/xcode-release-notes/xcode-11_2-release-notes#Swift
- https://bugs.swift.org/browse/SR-11704

There isn't a good workaround for this other than to ensure the framework binaries are built with the same version of Swift that your consuming project.

**Comment by palpatim** [comment] 2020-11-07 00:58
I'm marking this issue with the "service" label to indicate that we believe it's related to an Apple/Swift bug, not a project issue. I'm also marking it "work in progress" because I want to dig into the project a bit more to see if I can find where this is coming from. When I create a dead simple project with a public type named the same as the module itself, and set the `BUILD_LIBRARIES_FOR_DISTRIBUTION` flag, I'm able to import a binary with no problems. Something about the complexity of the AWSMobileClient project is triggering the issue, so if we can find what that trigger is, we might gain some insight into a way to workaround the issue without renaming the module or the AWSMobileClient type itself (both of which would be significantly breaking changes).

**Comment by johnayers84** [comment] 2020-11-13 04:47
Any update to this issue? We're seeing an identical problem using Xcode 12.2/Swift 5.3.1 with release v2.19.1

**Comment by rpotze** [comment] 2020-12-08 12:05
Same issue with SDK 2.19 and Xcode 12.2:
Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler: [......]/Frameworks/AWSMobileClient.framework/Modules/AWSMobileClient.swiftmodule/arm64-apple-ios.swiftmodule

Same remedies tried as described above, to no avail. This is seriously impacting our ability to work with Cognito.
For me, breaking changes would be preferable to non-working libraries.

**Comment by palpatim** [comment] 2020-12-14 18:37
I have reproduced this with a [barebones sample project](https://github.com/palpatim/swift-module-compat-test) and verified that the bug is not yet fixed as of Xcode 12.2.

Unfortunately, we can't find any good backwards-compatible options. At this point, we're exploring a couple of options:

- Introduce a new module that simply re-packages the same source files of the AWSMobileClient under a different module name
- Introduce a new module that builds using [XCFrameworks ](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages), which might solve the issue, although we haven't verified that yet.

   Even if it doesn't solve the issue, we're exploring building binaries using XCFrameworks. This will help us work around the fat-binary issue that is going to become more of a problem as adoption of M1-based Macs increases.

We'll update this issue as we make progress.

**Comment by jaelee1993** [comment] 2021-01-12 18:11
Hey guys, was there any solution to this?
Setting **BUILD_LIBRARIES_FOR_DISTRIBUTION** to _YES_ did not work for me.

**Comment by palpatim** [comment] 2021-01-29 17:40
@jaelee1993 The Swift bug is still unresolved. However, we're releasing support for XCFrameworks in 2.22.1, which will provide a new way for consuming these binary frameworks.

**Comment by palpatim** [comment] 2021-01-29 21:48
As of 2.21.1, we distribute the AWSMobileClient binary as an XCFramework with the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag enabled. Please see [Carthage installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframeworks-recommended) or [XCFramework installation instructions](https://github.com/aws-amplify/aws-sdk-ios#xcframework-setup) in the README for more info.

Do note that you will have to import a different module name; for backwards compatibility with CocoaPods users, we had to distribute the XCFramework binary under a different target. The usage at the call site remains the same:

**YourAppCode.swift**
```
import AWSMobileClientXCF

// later, at the call site...
AWSMobileClient.initialize() { _ in print("AWSMobileClient initalized") }
```

Let us know if you have any questions.

**Comment by abildgaard** [comment] 2021-01-30 22:45
@palpatim very happy to see XCFramework release. 

Sadly when we use the 2.22.1 XCFramework our app crashes with the following error message:

**Fatal error: Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions'**

This happens when the following calls are made after we have initialized the AWSMobileClient :

```
mobileClient = AWSMobileClient(configuration: configuration)
....

 mobileClient.initialize { (userState, error) in
    // show the userState
}

....
 mobileClient.showSignIn(navigationController: navigationController, hostedUIOptions: hostedUIOptions) { (userState, error) in 
    // launch login screen ....
}

...


```

We don't use the  `AWSMobileClient.default().initialize()`  as we to use the `AWSMobileClient(configuration: configuration)` , initializing from a configuration out of necessity. This code works using the 2.22.0 frameworks (non XCFramework) compiled using Carthage.

Any suggestions ?

**Comment by abildgaard** [comment] 2021-02-01 05:10
@palpatim very happy to see XCFramework release.

Sadly when we use the 2.22.1 XCFramework our app crashes with the following error message:

Fatal error: Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions'

This happens when either of the following calls are made after we have initialized the AWSMobileClient:

import AWSMobileClientXCF
...
mobileClient = AWSMobileClient(configuration: configuration)
....

 mobileClient.initialize { (userState, error) in
    // show the userState
}

....

 mobileClient.showSignIn(navigationController: navigationController, hostedUIOptions: hostedUIOptions) { (userState, error) in 
    // launch login screen ....
}

We don't use the AWSMobileClient.default() to initialize but use the AWSMobileClient(configuration: configuration) out of necessity. This code works using the 2.22.0 frameworks (non XCFramework) compiled using Carthage.

Any suggestions ?

using: Xcode 12.4 / iOS 14.4 / AWS SDK iOS 2.22.1 (XCFramework)

**Comment by abildgaard** [comment] 2021-02-01 20:13
@palpatim very happy to see XCFramework release.

Sadly when we use the 2.22.1 XCFramework our app crashes with the following error message:

**Fatal error: Use of unimplemented initializer 'init()' for class 'AWSMobileClientXCF.SignInUIOptions'**

This happens when the mobileClient.showSignIn() call is made after we have initialized the AWSMobileClient:

import AWSMobileClientXCF
...
mobileClient = AWSMobileClient(configuration: configuration)
let hostedUIOptions = HostedUIOptions(scopes: ["openid"])
mobileClient.showSignIn(navigationController: navigationController, hostedUIOptions: hostedUIOptions) { (userState, error) in 
       // launch login screen ....
}

As you see we don't use the AWSMobileClient.default() to initialize but use the AWSMobileClient(configuration: configuration) out of necessity. 

This code works using the 2.22.0 frameworks (non XCFramework) compiled using Carthage.

Any suggestions ?


using: Xcode 12.4 / iOS 14.4 / AWS SDK iOS 2.22.1 (XCFramework)

**Comment by palpatim** [comment] 2021-02-05 16:54
https://github.com/aws-amplify/aws-sdk-ios/issues/3410 closed by https://github.com/aws-amplify/aws-sdk-ios/issues/3033.

I'm optimistically closing this issue since we haven't heard any other issues on this. Please feel free to open a new issue with details if you have problems with the XCFrameworks distributions.

**Closed by palpatim** 2021-02-05 16:54 UTC
Labels: bug, build, mobile client, requesting info, service
