### ISSUE TITLE
Warning "was built for iOS + iOS simulator" at compiling.

### ISSUE THREAD

**Issue by David-Madpixel** [aws-amplify/aws-sdk-ios#3370] opened 2021-01-14 10:48 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as detailed as possible and help us help you.

I get the warning when trying to compile.

"Building for iOS, but the linked and embedded framework 'AWSS3.framework' was built for iOS + iOS Simulator."
"Building for iOS, but the linked and embedded framework 'AWSCore.framework' was built for iOS + iOS Simulator."

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

AWSS3

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]

2.22.0

 - Dependency Manager: [e.g. Cocoapods, Carthage]

Downloaded latest sdk zip.

 - Swift Version : [e.g. 4.0]

Objective C.

 - Xcode Version: [e.g. 11.4]

12.3

**Comment by wooj2** [comment] 2021-01-14 16:50
Hi @David-Madpixel ,

Thanks for reaching out.

I suspect this is an incompatibility with the way we do our binary releases with Carthage.  I believe we need to update our script to support XCode 12.3, located here:
https://github.com/aws-amplify/aws-sdk-ios/blame/fe7c6883d6b1b2a92211d0ffcd47c1034de3035b/CircleciScripts/carthage-build.sh#L39

**Comment by wooj2** [comment] 2021-01-14 23:41
This seems to be a duplicate of this issue:
https://github.com/aws-amplify/aws-sdk-ios/issues/3346

**Closed by wooj2** 2021-01-14 23:41 UTC
Labels: bug, build
