### ISSUE TITLE
AWS Mobile Hub Analytics Custom Event Fail.

### ISSUE THREAD

**Issue by sykzero2001** [aws-amplify/aws-sdk-ios#1244] opened 2019-02-21 06:43 UTC
**Describe the bug**
I use the AWSPinpoint Sdk in Xode(IOS),and I success build an endpoint even I can Adding Custom Endpoint Attributes.But when I try to add a Custom Event,It look fine but I can't see this event in the Pinpoint>Analytics>Events 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:ios

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muellerfr** [comment] 2019-02-22 04:46
@sykzero2001, I transferred this to the actual SDK repo to answer. If documentation updates are required we will make them.

**Comment by palpatim** [comment] 2019-02-25 21:56
@sykzero2001 

I'm not able to replicate this locally. I note that you have reversed the sense of the `task.error` check--the above code will be logging `update` when `task.error` is ***NOT*** nil. Did you copy this ObjectiveC code from somewhere? If so, can you provide a link so we can ensure that is correct in the sample?

Assuming that fixing the error check doesn't point you to the root cause of the problem, some other questions: 
* What version of the SDK are you using?
* Can you show your Pinpoint setup code?
* How are you invoking these requests? 
* Did you set up your sample to submit as an unauthenticated, or authenticated user? If both, is there a difference in behavior when logged in vs. not?
* Can you post the IAM policies associated with your auth & unauth roles? (If you followed the instructions you pointed to and used `amplify add auth` to set up Pinpoint, then the roles should be set up correctly, but it would be great to double check. )

**Comment by sykzero2001** [comment] 2019-02-27 03:21
![2019-02-27 11 17 30](https://user-images.githubusercontent.com/13185357/53463405-c4e45000-3a81-11e9-8cf9-50655092e652.png)
![2019-02-27 11 17 46](https://user-images.githubusercontent.com/13185357/53463412-c877d700-3a81-11e9-9064-13b09ae20fc0.png)
![2019-02-27 11 18 20](https://user-images.githubusercontent.com/13185357/53463417-cb72c780-3a81-11e9-9ee2-28ebf4afebcc.png)
![2019-02-27 11 18 33](https://user-images.githubusercontent.com/13185357/53463424-cdd52180-3a81-11e9-9735-f1649312edbe.png)

**Comment by palpatim** [comment] 2019-02-27 15:11
Thanks for the additional context. I replaced the image of your awsconfiguration.json to obfuscate the sensitive information like pool ID and bucket.

> I note that you have reversed the sense of the `task.error` check--the above code will be logging `update` when `task.error` is _**NOT**_ nil.

When you correct the error condition as I noted above, does your code display any errors during the `submitEventsWithCompletionBlock` execution? 

And finally:

> Did you copy this ObjectiveC code from somewhere? If so, can you provide a link so we can ensure that is correct in the sample?

**Comment by sykzero2001** [comment] 2019-03-04 03:01
![2019-03-04 10 59 03](https://user-images.githubusercontent.com/13185357/53708107-d015f200-3e6c-11e9-930f-88ca0f8813e2.png)

**Comment by sykzero2001** [comment] 2019-03-04 03:23
I will add the Permission PutEvents in Pinpoint IAM,It's work!
But I confuse of that, why my partner use Andorid sdk but he didn't need to add this Permission and it also work?

**Comment by palpatim** [comment] 2019-03-04 17:02
@sykzero2001 

Thanks for the update, and I'm glad that the updated IAM policy resolved your issue. It sounds like we there is a difference in the call patterns on iOS vs. Android. What version of the Android Pinpoint SDK is your Android app using?

**Comment by sykzero2001** [comment] 2019-03-05 01:44
![2019-03-05 09 42 56](https://user-images.githubusercontent.com/13185357/53774865-234e7a00-3f2b-11e9-900a-ba3d682314f1.png)
Andorid's doc is
[https://docs.aws.amazon.com/aws-mobile/latest/developerguide/mobile-hub-add-aws-mobile-analytics.html](url)

**Closed** 2019-05-02 22:21 UTC
Labels: Pinpoint, Question
