### ISSUE TITLE
Crash Report in AWSIoTMQTTClient.m

### ISSUE THREAD

**Issue by fattarzan** [aws-amplify/aws-sdk-ios#5389] opened 2024-06-24 03:40 UTC
**Describe the bug**

===== Crash  =====

비정상 종료: Thread #1
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000009f21975f0

AWSIoTMQTTClient.m - 1037번째 줄
-[AWSIoTMQTTClient session:handleEvent:] + 1037

================

![스크린샷 2024-06-24 오후 12 38 02](https://github.com/aws-amplify/aws-sdk-ios/assets/11714931/9dd50d0b-5d44-46e6-a020-f03e1386ba5f)

- AWSIoT (2.36.3):
    - AWSCore (= 2.36.3)

Thanks

**Comment by fattarzan** [comment] 2024-06-28 04:02
Hi

"We don't have logs because the issue occurs intermittently, but we have
identified the location in the code."



AWSDDLogInfo(@"Auto-resubscribe is enabled. Resubscribing to topics.");
                for (AWSIoTMQTTTopicModel *topic in
self.topicListeners.allValues) {
                    [self.session subscribeToTopic:topic.topic
atLevel:topic.qos];
                }








2024년 6월 25일 (화) 오후 1:14, Harsh ***@***.***>님이 작성:

**Comment by ruisebas** [comment] 2024-06-28 15:19
Hi @fattarzan, could you please share the full symbolicated crashlog? It contains information that could help us identify the root cause.

Also, do you know if there's a specific condition or use case that results in this crash?

**Comment by bbx1209** [comment] 2024-07-09 02:47
Crashed: Thread
0  libobjc.A.dylib                0x3120 objc_retain + 16
1  CoreFoundation                 0x4c568 <redacted> + 168
2  **********                     0x4431d0 -[AWSIoTMQTTClient session:handleEvent:] + 1049 (AWSIoTMQTTClient.m:1049)
3  **********                     0x464f5c -[AWSMQTTSession decoder:newMessage:] + 414 (AWSMQTTSession.m:414)
4  **********                     0x461fc8 -[AWSMQTTDecoder stream:handleEvent:] + 153 (AWSMQTTDecoder.m:153)
5  CoreFoundation                 0xf86c0 <redacted> + 212
6  CoreFoundation                 0x110270 <redacted> + 284
7  CoreFoundation                 0x10360c <redacted> + 300
8  CFNetwork                      0x147a30 _CFNetworkErrorGetLocalizedDescription + 186056
9  CFNetwork                      0x14e974 _CFNetworkErrorGetLocalizedDescription + 214540
10 CoreFoundation                 0x112720 <redacted> + 1192
11 CoreFoundation                 0xb3448 <redacted> + 24
12 CoreFoundation                 0xc3578 <redacted> + 204
13 CoreFoundation                 0x5734 <redacted> + 256
14 CoreFoundation                 0xae08 <redacted> + 768
15 CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
16 Foundation                     0x17eac <redacted> + 232
17 **********                     0x441d44 -[AWSIoTMQTTClient openStreams:] + 763 (AWSIoTMQTTClient.m:763)
18 Foundation                     0x64bdc <redacted> + 792
19 libsystem_pthread.dylib        0x3338 _pthread_start + 116
20 libsystem_pthread.dylib        0x1938 thread_start + 8

**Comment by thisisabhash** [comment] 2024-07-18 15:42
We have merged a fix and will update the ticket when a new version is released.

**Comment by ruisebas** [comment] 2024-07-25 02:03
The fix has been released in [2.36.6](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.36.6)

**Closed by ruisebas** 2024-07-25 02:03 UTC
Labels: bug, iot
