### ISSUE TITLE
Cognito auth  with federatedSignIn return Invalid login token

### ISSUE THREAD

**Issue by morris-lu** [aws-amplify/aws-sdk-ios#2296] opened 2020-02-18 08:54 UTC
**Which AWS service(s) are affected?**
- AWSMobileClient
- AWSCognitoAuth

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
2.12.7
 - Dependency Manager: [e.g. Cocoapods, Carthage]
Cocoapods
 - Swift Version : [e.g. 4.0]
Swift 5

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
iPhone 11
 - iOS Version: [e.g. iOS 11.4]
iOS 13.2.2
 - Specific to simulators:
iPhone 11

Currently, I use CognitoAuth to setup my identity provider,
and I login/signup successfully also create a user in Userpool, but SDK log said 

```
Response body:
{"__type":"NotAuthorizedException","message":"Invalid login token. Token is expired."}
2020-02-18 16:43:01:088 Giant[80048:3203996] GetId failed. Error is [Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Invalid login token. Token is expired.}]
```

here is my code 

```
func socialLogin(via provider: IdentityProvider) {
var configuration: AWSCognitoAuthConfiguration?
        let appClientId = Constant.getApplClientId
        let webDomain = Constant.webDomain
        switch provider {
        case .facebook:
            configuration = AWSCognitoAuthConfiguration(
                appClientId: appClientId,
                appClientSecret: nil,
                scopes: Set<String>(["openid","email","profile"]),
                signInRedirectUri: "myapp://",
                signOutRedirectUri: "myapp://",
                webDomain: Constant.webDomain,
                identityProvider: "Facebook",
                idpIdentifier: nil,
                userPoolIdForEnablingASF: nil)
        case .google:
            configuration = AWSCognitoAuthConfiguration(
                appClientId: appClientId,
                appClientSecret: nil,
                scopes: Set<String>(["openid","email","profile"]),
                signInRedirectUri: "myapp://",
                signOutRedirectUri: "myapp://",
                webDomain: webDomain,
                identityProvider: "Google",
                idpIdentifier: nil,
                userPoolIdForEnablingASF: nil)
        default:
            break
        }

        guard configuration != nil else { return }
        AWSCognitoAuth.registerCognitoAuth(with: configuration!, forKey: "cognitoAuth")
        auth = AWSCognitoAuth(forKey: "cognitoAuth")
        auth?.delegate = self

        auth?.getSession { (session:AWSCognitoAuthUserSession?, error:Error?) in
            if let error = error {
                print("login error: ", error)

            }else {
                if let token = session?.idToken {
                    AWSMobileClient.default().federatedSignIn(providerName: provider.rawValue, token: token.tokenString, completionHandler: { (state, error) in
                        DispatchQueue.main.async {
                            if let state = state {
                                switch state {
                                case .signedIn:
                                    print("signin")
                                default:
                                    break
                                }
                            } else if let error = error as? AWSMobileClientError {
                                switch(error) {
                                case .userNotFound(let message):
                                    print(message)
                                case .invalidParameter(let message):
                                    print(message)
                                case .notAuthorized(let message):
                                    print(message)
                                default:
                                    break
                                }
                            }
                        }
                    })
                }
            }
        }
    }
```

How can I fix the problem? Thank you.

**Comment by wooj2** [comment] 2020-02-18 19:27
Hey Morris-lu,

Thanks for getting in touch with us regarding this matter.

First, we do not recommend you call `AWSCognitoAuth` directly, as this is a relatively low level library that is used by the AWSMobileClient.  

Looking at your code, it looks like you are attempting to use a social provider as an identity provider (AuthN), and then access AWS services with an identity pool.  For this use case, we support the Amazon Cognito Hosted UI, which you can find more information located here:
https://aws-amplify.github.io/docs/ios/authentication#using-hosted-ui-for-authentication

After going through the setup, all you should have to do to launch the signIn() page is:
```
// Present the Hosted UI sign in.
AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: hostedUIOptions) { (userState, error) in
    if let error = error as? AWSMobileClientError {
        print(error.localizedDescription)
    }
    if let userState = userState {
        print("Status: \(userState.rawValue)")
    }
}
```

Best of luck!

**Comment by morris-lu** [comment] 2020-02-21 02:56
Hi @wooj2,
Thanks for the reply. I'll try showSignIn later.  Thank you.

**Comment by morris-lu** [comment] 2020-02-21 03:45
Hi @wooj2 
ShowSignIn works perfectly, sign up with Facebook and Google also create user, but I got this error sometimes
```
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: Invalid user attributes: email: Attribute cannot be updated.
 })
```
Here is my code
```
  @IBAction func signIn(_ sender:UIButton) {
        let facebookSignIn = HostedUIOptions(identityProvider: "Facebook")
        let googleSignIn = HostedUIOptions(identityProvider: "Google")

        AWSMobileClient.default().showSignIn(navigationController: self.navigationController!, hostedUIOptions: googleSignIn) { (userState, error) in
            print("error",error)
            if let error = error as? AWSMobileClientError {
                print("Status error: ",error.localizedDescription)
            }
            if let userState = userState {
                print("Status: \(userState.rawValue)")
            }
        }
    }

```

Thank you

**Comment by morris-lu** [comment] 2020-02-24 03:35
Hi @wooj2,

![截圖 2020-02-24 11 30 52](https://user-images.githubusercontent.com/40878125/75127286-38528900-56f9-11ea-8e51-8760e8657742.png)
Currently, I change my user pool attribute to Username fixed the problem.

I'm wondering why it shows `invalid token` when I using CognitoAuth.getssion function and showSignIn won't. I also check both access token and id token on JWT, the format looks the same.

Thank you.

**Comment by wooj2** [comment] 2020-02-24 04:41
@morris-lu 
Sorry for the delay, and glad that you were able to find a solution to the issue with regards to `email: Attribute cannot be updated.`.

With regards to CognitoAuth getSession, I don't believe the code samples you provided above were intended to work like that, so the service was complaining about an invalid token.  With using HostedUI, it was intended to be a higher level API to avoid some of the lower level complexities -- so, that's probably why you are no longer seeing the error :).

I'm going to close this issue for now, but feel free to re-open if there are additional problems.

**Closed by wooj2** 2020-02-24 04:41 UTC
Labels: AWSMobileClient, Cognito

**Comment by zhou-meta** [comment] 2022-01-04 09:25
Got the same issue, the error message was extremely confusing - "NotAuthorizedException: Invalid login token. Token is expired."
