### ISSUE TITLE
AWS Cogito Crashes

### ISSUE THREAD

**Issue by bfallon** [aws-amplify/aws-sdk-ios#1682] opened 2019-07-24 16:34 UTC
**Describe the bug**
Reviewing Crashlytics reports, the SDK has a lot of crashes.

**To Reproduce**
There are no steps to reproduce this issue.

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
We expect the SDK to not crash. 

**Code**
Below please find the classes and line numbers where the app crashes:

AWSTaskCompletionSource.m 
line 56 -[AWSTaskCompletionSource setError:]

AWSTaskCompletionSource.m 
line 49 -[AWSTaskCompletionSource setResult:]

AWSMobileClientExtensions.swift line 121
specialized closure #2 in AWSMobileClient.logins()

**Environment(please complete the following information):**
 - SDK Version: 2.9.6
 - Dependency Manager: CocoaPods
 - Swift Version: 4

**Device Information (please complete the following information):**
 - Device: Multiple iPhone devices
 - iOS Version: iOS 11 and iOS 12
 - Specific to simulators: This is specific to iOS devices.

**Comment by palpatim** [comment] 2019-07-29 14:12
I believe this is a dupe of #1505

**Comment by palpatim** [comment] 2019-08-23 03:30
This was released on [2.10.3](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.10.3). Please let us know if you continue to experience problems.

**Closed** 2019-08-23 03:31 UTC
Labels: AWSMobileClient, Bug, Duplicate
