### ISSUE TITLE
File upload very slow for iOS 15

### ISSUE THREAD

**Issue by rabinpun** [aws-amplify/aws-sdk-ios#4169] opened 2022-06-02 03:16 UTC
Why is my aws upload very slow it was very fast for ios 14.7 version

2.27.9

I am using the sample project to test the speed

Environment(please complete the following information):
 - SDK Version: 2.27.9
 - Dependency Manager: SPM
 - Swift Version : 5.5.1

Device Information 
 - Device: iphone 7 
 - iOS Version: ios 15.4

**Comment by thisisabhash** [comment] 2022-06-17 18:49
Hello, There is an ongoing discussion about a similar issue and under investigation
https://github.com/aws-amplify/amplify-ios/issues/1542

**Comment by diegocstn** [comment] 2022-06-24 17:34
Duplicate of https://github.com/aws-amplify/amplify-ios/issues/1542

**Closed by diegocstn** 2022-06-24 17:34 UTC
Labels: duplicate, s3
