### ISSUE TITLE
Received an MQTT session connection error

### ISSUE THREAD

**Issue by Maher-tech** [aws-amplify/aws-sdk-ios#2005] opened 2019-10-20 15:52 UTC
Connection  failure with certificate in bundle

 - SDK Version: 
             pod 'AWSMobileClient', '~> 2.11.1'
              pod 'AWSIoT', '~> 2.11.1'
 - Dependency Manager:  Cocoapods
 -Swift Version : [ 4.0]

my implementation: 
//     Initialize AWSMobileClient for authorization
    AWSMobileClient.default().initialize { (userState, error) in
      guard error == nil else {
        print("Failed to initialize AWSMobileClient. Error: \(error!.localizedDescription)")
        return
      }
      print("AWSMobileClient initialized.")
    }
    AWSDDLog.sharedInstance.logLevel = .verbose
    AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
    // Init IOT
    let iotEndPoint = AWSEndpoint(urlString: "https//a1brkcziqhilz7-ats.iot.eu-central-1.amazonaws.com")

    let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.EUCentral1,
                                                                identityPoolId:"eu-central-1:f90c9590-3835-4a4c-87e1-edb54c687c28")
    // Configuration for AWSIoT control plane APIs
    let iotConfiguration = AWSServiceConfiguration(region: .EUCentral1, credentialsProvider: credentialsProvider)

    // Configuration for AWSIoT data plane APIs
    let iotDataConfiguration = AWSServiceConfiguration(region: .EUCentral1,
                                                       endpoint: iotEndPoint,
                                                       credentialsProvider: credentialsProvider)
    AWSServiceManager.default().defaultServiceConfiguration = iotConfiguration

    iotManager = AWSIoTManager.default()
    iot = AWSIoT.default()

    AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: ASWIoTDataManager)
    iotDataManager = AWSIoTDataManager(forKey: ASWIoTDataManager)

    func mqttEventCallback( _ status: AWSIoTMQTTStatus )
    {
      DispatchQueue.main.async {
        print("connection status = \(status.rawValue)")
        switch(status)
        {
        case .connecting:
          print("Connecting...")
        case .connected:
          print("Connected")
        case .disconnected:
          print("Disconnected")
        case .connectionRefused:
         print("Connection Refused")
        case .connectionError:
          print("Connection Error")
        case .protocolError:
         print("Protocol Error")
        default:
          print("unknown state: \(status.rawValue)")
        }
        NotificationCenter.default.post( name: Notification.Name(rawValue: "connectionStatusChanged"), object: self )
      }
    }
    if (connected == false)
    {
      let defaults = UserDefaults.standard

      var certificateId = defaults.string( forKey: "certificateId")

      if (certificateId == nil)
      {
        DispatchQueue.main.async {
          print("No identity available, searching bundle...")
        }

        // No certificate ID has been stored in the user defaults; check to see if any .p12 files
        // exist in the bundle.
        let myBundle = Bundle.main
        let myImages = myBundle.paths(forResourcesOfType: "p12" as String, inDirectory:nil)
        let uuid = UUID().uuidString;

        if (myImages.count > 0) {        
          if let data = try? Data(contentsOf: URL(fileURLWithPath: myImages[0])) {
            DispatchQueue.main.async {
             print ("found identity \(myImages[0]), importing...")
            }
            if AWSIoTManager.importIdentity( fromPKCS12Data: data, passPhrase:"", certificateId:myImages[0]) {
              defaults.set(myImages[0], forKey:"certificateId")
              defaults.set("from-bundle", forKey:"certificateArn")
              DispatchQueue.main.async {
                print("Using certificate: \(myImages[0]))")
                self.iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:myImages[0], statusCallback: mqttEventCallback)
              }
            }
          }
        }
        certificateId = defaults.string( forKey: "certificateId")
      }
      else
      {
        let uuid = UUID().uuidString;
        iotDataManager.connect( withClientId: uuid, cleanSession:true, certificateId:certificateId!, statusCallback: mqttEventCallback)
      }
    }
    else
    {
      print("Disconnecting...")

      DispatchQueue.global(qos: DispatchQoS.QoSClass.default).async {
        self.iotDataManager.disconnect();
        DispatchQueue.main.async {
          self.connected = false
          print("Connect")
        }
      }
    }

///// log///////

AWSMobileClient initialized.
2019-10-20 16:39:07:621 aqua-iot[84268:1565646] Retrieving credentials from keychain
2019-10-20 16:39:07:627 aqua-iot[84268:1565646] Initializing AWSIoTMqttConfiguration with KeepAlive:300.000000, baseReconnectTime:1.000000,minimumConnectionTime:20.000000, maximumReconnectTime:128.000000, autoResubscribe:Enabled, lwt topic: message: 
2019-10-20 16:40:17:782 aqua-iot[84268:1565646] <<<NSThread: 0x600002336800>{number = 1, name = main}>>In connectWithClientID
2019-10-20 16:40:17:782 aqua-iot[84268:1565646] hostName: (null)
2019-10-20 16:40:17:782 aqua-iot[84268:1565646] URL: https//a1brkcziqhilz7-ats.iot.eu-central-1.amazonaws.com
2019-10-20 16:40:17:785 aqua-iot[84268:1565646] user metadata is : ?SDK=iOS&Version=2.11.1
2019-10-20 16:40:17:785 aqua-iot[84268:1565646] Metrics collection is: Enabled
2019-10-20 16:40:17:787 aqua-iot[84268:1565646] -[AWSMQTTSession initWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetainFlag:publishRetryThrottle:] [Line 82], Thread:<NSThread: 0x600002336800>{number = 1, name = main} 
2019-10-20 16:40:17:787 aqua-iot[84268:1565646] +[AWSMQTTMessage connectMessageWithClientId:userName:password:keepAlive:cleanSession:willTopic:willMsg:willQoS:willRetain:] [Line 66], Thread:<NSThread: 0x600002336800>{number = 1, name = main} 
2019-10-20 16:40:17:787 aqua-iot[84268:1565646] Creating AWSMQTTMessage with raw data >>>>> <00044d51 54540482 012c0024 37343337 45363835 2d454238 312d3444 43312d41 4142332d 33414333 43354136 36434645 00173f53 444b3d69 4f532656 65727369 6f6e3d32 2e31312e 31> <<<<<
2019-10-20 16:40:17.790787+0100 aqua-iot[84268:1566335] CFNetwork SSLHandshake failed (-9810)
2019-10-20 16:40:17:789 aqua-iot[84268:1566335] <<<NSThread: 0x6000023b1f00>{number = 5, name = (null)}>> Initializing MQTTEncoder and MQTTDecoder streams
2019-10-20 16:40:17.800345+0100 aqua-iot[84268:1566335] TCP Conn 0x0 SSLHandshake failed (-9810)
2019-10-20 16:40:17:789 aqua-iot[84268:1566335] opening encoder stream.
2019-10-20 16:40:17:790 aqua-iot[84268:1566335] opening decoder stream.
2019-10-20 16:40:17:800 aqua-iot[84268:1566335] -[AWSMQTTDecoder stream:handleEvent:] [Line 57] EventCode:1, stream: <__NSCFInputStream: 0x60000043ba80>, Thread: <NSThread: 0x6000023b1f00>{number = 5, name = (null)}
2019-10-20 16:40:17:800 aqua-iot[84268:1566335] -[AWSMQTTDecoder stream:handleEvent:] [Line 57] EventCode:8, stream: <__NSCFInputStream: 0x60000043ba80>, Thread: <NSThread: 0x6000023b1f00>{number = 5, name = (null)}
2019-10-20 16:40:17:800 aqua-iot[84268:1566335] -[AWSMQTTSession decoder:handleEvent:] [Line 346] eventCode:2
connection status = 1
Connecting...
2019-10-20 16:40:17:800 aqua-iot[84268:1566335] MQTT session error, code: 3
2019-10-20 16:40:17:814 aqua-iot[84268:1566335] closing encoder stream.
2019-10-20 16:40:17:815 aqua-iot[84268:1566335] closing decoder stream.
2019-10-20 16:40:18:815 aqua-iot[84268:1566335] MQTTSessionDelegate handleEvent: 3
2019-10-20 16:40:18:815 aqua-iot[84268:1566335] MQTTSessionEventConnectionError: Received an MQTT session connection error
connection status = 5
Connection Error

someone can help with this error PLZ !!

**Comment by palpatim** [comment] 2019-10-21 15:18
@Maher-tech This seems to be a dupe of #2002. What is different about this issue?

**Comment by Maher-tech** [comment] 2019-10-21 16:58
yeah its the same one

**Comment by palpatim** [comment] 2019-10-21 18:20
Dupe of #2002

**Closed by palpatim** 2019-10-21 18:20 UTC
