### ISSUE TITLE
Crash  -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[7]

### ISSUE THREAD

**Issue by pablogeek** [aws-amplify/aws-sdk-ios#1060] opened 2018-10-10 13:49 UTC
Hello guys,

I'm having this crash.

**Describe the bug**

**To Reproduce**
Some users are having this when upload

**Which AWS service(s) are affected?**
S3
**Expected behavior**
It doesn't crash

**Environment(please complete the following information):**
 - SDK Version: 2.6.31
 - Dependency Manager:  Cocoapods
 - Swift Version : 4.1

**Device Information (please complete the following information):**
 - Device: different iOS devices
 - iOS Version: iOS 12

**Additional context**

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x18ccb2ef8 __exceptionPreprocess
1  libobjc.A.dylib                0x18be80a40 objc_exception_throw
2  CoreFoundation                 0x18cc2885c _CFArgv
3  CoreFoundation                 0x18cbaeeb0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
4  CoreFoundation                 0x18cb9f9f4 +[NSDictionary dictionaryWithObjects:forKeys:count:]
5  AWSS3                          0x100d60c0c __259+[AWSS3TransferUtilityDatabaseHelper insertTransferRequestInDB:nsURLSessionID:taskIdentifier:transferType:bucket:key:partNumber:multiPartID:eTag:file:temporaryFileCreated:contentLength:status:retryCount:requestHeadersJSON:requestParametersJSON:databaseQueue:]_block_invoke (AWSS3TransferUtilityDatabaseHelper.m:313)
6  AWSCore                        0x100a67350 __33-[AWSFMDatabaseQueue inDatabase:]_block_invoke (AWSFMDatabaseQueue.m:157)
7  libdispatch.dylib              0x18c6eb484 _dispatch_client_callout
8  libdispatch.dylib              0x18c698610 _dispatch_lane_barrier_sync_invoke_and_complete
9  AWSCore                        0x100a672c8 -[AWSFMDatabaseQueue inDatabase:] (AWSFMDatabaseQueue.m:171)
10 AWSS3                          0x100d60944 +[AWSS3TransferUtilityDatabaseHelper insertTransferRequestInDB:nsURLSessionID:taskIdentifier:transferType:bucket:key:partNumber:multiPartID:eTag:file:temporaryFileCreated:contentLength:status:retryCount:requestHeadersJSON:requestParametersJSON:databaseQueue:] (AWSS3TransferUtilityDatabaseHelper.m:311)
11 AWSS3                          0x100d60230 +[AWSS3TransferUtilityDatabaseHelper insertMultiPartUploadRequestInDB:databaseQueue:] (AWSS3TransferUtilityDatabaseHelper.m:240)
12 AWSS3                          0x100d55e20 __130-[AWSS3TransferUtility internalUploadFileUsingMultiPart:bucket:key:contentType:expression:temporaryFileCreated:completionHandler:]_block_invoke (AWSS3TransferUtility.m:1264)
13 AWSCore                        0x100a92e7c __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke (AWSTask.m:331)
14 AWSCore                        0x100a603ec __30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:66)
15 AWSCore                        0x100a60958 -[AWSExecutor execute:] (AWSExecutor.m:131)
16 AWSCore                        0x100a92a7c -[AWSTask runContinuations] (AWSTask.m:308)
17 AWSCore                        0x100a925c0 -[AWSTask trySetResult:] (AWSTask.m:247)
18 AWSCore                        0x100a93bf0 -[AWSTaskCompletionSource setResult:] (AWSTaskCompletionSource.m:45)
19 AWSCore                        0x100aaf5bc __61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke (AWSURLSessionManager.m:373)
20 AWSCore                        0x100a9350c __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke (AWSTask.m:398)
21 AWSCore                        0x100a92e7c __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke (AWSTask.m:331)
22 AWSCore                        0x100a603ec __30+[AWSExecutor defaultExecutor]_block_invoke_2 (AWSExecutor.m:66)
23 AWSCore                        0x100a60958 -[AWSExecutor execute:] (AWSExecutor.m:131)
24 AWSCore                        0x100a92ce4 -[AWSTask continueWithExecutor:block:cancellationToken:] (AWSTask.m:368)
25 AWSCore                        0x100a9346c -[AWSTask continueWithExecutor:successBlock:cancellationToken:] (AWSTask.m:394)
26 AWSCore                        0x100a935ac -[AWSTask continueWithSuccessBlock:] (AWSTask.m:404)
27 AWSCore                        0x100aae738 -[AWSURLSessionMan
```

**Comment by cbommas** [comment] 2018-10-10 15:11
@pablogeek 
I will take a look into this and post an update here with my findings.

**Comment by Dellybro** [comment] 2018-10-15 19:59
This happens to me too, but with AWSAPIGateway, and it's affecting some users, but not all users. And we can not track down the issue at all. The users are on iOS 12, but some other users who don't have this issue are also on iOS 12. 

Essentially the response from invoking my API gateway ends up being nil. and it crashes because i attempt to use an object that isn't there, but API Gateway should never return a nil object.

On top of this I am using an unauthenticated client because these API request which are failing are for users who are attempting to "login" so I set my credentials provider to NIL.

This is affecting our live version heavily, and i hope to get a response quick.

**Comment by cbommas** [comment] 2018-10-16 20:53
@Dellybro 
This is a crash that is specific to the persistence layer of the Transfer Utility and not related to the API Gateway - can you post a stack trace that will help confirm if it is the same issue.

**Comment by cbommas** [comment] 2018-10-16 20:55
@pablogeek 
I have been able to mimic this issue, but not reproduce it. Essentially, what is happening is that the MultiPart upload ID is null when it is trying to be inserted into the DB.

Have you been able to reproduce this in your testing?

**Comment by pablogeek** [comment] 2018-10-16 22:06
@cbommas I haven't been able to reproduce the problem, this is happening only to few customers but multiple times. Seems once the app crashes, they restart the app, the upload restarts and then it crashes again.

**Comment by cbommas** [comment] 2018-10-27 12:15
@pablogeek 

Thanks for letting me know. I have tried it on my side as well without much success. In any case, I have put in some defensive code to make sure that the crash doesn't happen in this scenario - I am targeting this fix to be included in the next rev of the SDK. I will post back here once I have confirmation.

**Comment by pablogeek** [comment] 2018-10-27 15:05
@cbommas Thanks! let me know :)

**Comment by cbommas** [comment] 2018-11-08 16:41
@pablogeek 

The defensive code is included in the latest rev of the SDK (2.6.34) - Please give this a try when you can and let me know. 

I am going to go ahead and close this issue ( given that it has been difficult to reproduce and therefore validate). Please feel free to reopen if you see this issue is still occurring.

**Closed by cbommas** 2018-11-08 16:41 UTC
Labels: S3, bug

**Comment by pablogeek** [comment] 2019-04-05 19:29
@cbommas It is still happening in 2.6.35. :(

**Comment by cbommas** [comment] 2019-04-12 00:44
@pablogeek can you share the stacktrace, just to make sure that it is the same problem.

**Comment by dziwiedz** [comment] 2020-04-15 13:39
```
Thread 1 Queue : fmdb.<AWSFMDatabaseQueue: 0x282ccd8f0> (serial)
#0	0x00000001aca01ec4 in __pthread_kill ()
#1	0x00000001ac91d1d8 in pthread_kill$VARIANT$mp ()
#2	0x00000001ac871844 in abort ()
#3	0x00000001ac9ca7d4 in abort_message ()
#4	0x00000001ac9ca9c4 in demangling_terminate_handler() ()
#5	0x00000001ac932258 in _objc_terminate() ()
#6	0x00000001ac9d7304 in std::__terminate(void (*)()) ()
#7	0x00000001ac9d729c in std::terminate() ()
#8	0x00000001ac9321dc in objc_terminate ()
#9	0x0000000107b2abec in _dispatch_client_callout ()
#10	0x0000000107b39858 in _dispatch_lane_barrier_sync_invoke_and_complete ()
#11	0x0000000106961240 in -[AWSFMDatabaseQueue inDatabase:] at /**/
#12	0x0000000106fbc97c in +[AWSS3TransferUtilityDatabaseHelper updateTransferRequestInDB:partNumber:taskIdentifier:eTag:status:retry_count:databaseQueue:] at /**/
#13	0x0000000106fbffa8 in -[AWSS3TransferUtilityMultiPartUploadTask resume] at /**/
```

In our case it is happening when app is uploading file using multipart. When during upload app will go to background, then it will crash when app will enter foreground. Not each time, more randomly.  We are also using workaround provided here https://github.com/aws-amplify/aws-sdk-ios/issues/1513#issuecomment-531407454
