### ISSUE TITLE
AWSS3TransferUtility getMultiPartUploadTasks ,task status is error 

### ISSUE THREAD

**Issue by Guolanlan** [aws-amplify/aws-sdk-ios#3049] opened 2020-09-28 12:57 UTC
**Describe the bug**

The scenario is like this, the app is uploading videos in the foreground, the user manually kills the app, clicks on the app again to run, gets the tasks that have not been uploaded before, and continues uploading
I use the AWS3TransferUtility class and use the multiPartUploadfile. I get the transferUtility with the key in the block completed by regiestS3 and call the getMultiPartTask method, but the task status obtained is error, the transfer cannot be resumed, there is no progress, and I want to continue manually Pass, is there a way?

**To Reproduce**
1. Go to 'multiPartUploadfile'
2.  ‘ kill the App.'
3.  call 'getMultiPartUploadTasks' 
4. task status is error,and no upload,i don't resume task

**Observed Behavior**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.15.0]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Object-C Version
 - Xcode Version: [e.g. 11.5]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone11]
 - iOS Version: [e.g. iOS 13.3]
 - Specific to simulators:

Who Can hple me?? I'm going crazy。。。。

 

```

**Comment by Guolanlan** [comment] 2020-09-28 13:04
[AWSS3TransferUtility registerS3TransferUtilityWithConfiguration:serviceConfiguration transferUtilityConfiguration:transferUtilityConfig forKey:FS3S3TransferUtility completionHandler:^(NSError * _Nullable error) {
if (!self.multiPartProgressBlock) {
        self.multiPartProgressBlock =^(AWSS3TransferUtilityMultiPartUploadTask *task, NSProgress *progress){
        NSLog(@"续传进度 ////////////////  %lld  -  %lld ",progress.completedUnitCount,progress.totalUnitCount);
    };
        if (!self.mutipartCompleteBlock) {
        self.mutipartCompleteBlock = ^(AWSS3TransferUtilityMultiPartUploadTask *task,
                                       NSError * _Nullable error){
            NSLog(@"续传完成 //////////////// %ld - %@ ", (long)task.status,error);
        };
    }
    AWSS3TransferUtility * s3TransferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:FS3S3TransferUtility];
             NSArray * uploadAry = [[s3TransferUtility getMultiPartUploadTasks] result];
            NSLog(@"%@",uploadAry);
            
      for (AWSS3TransferUtilityMultiPartUploadTask *  task in uploadAry) {
          [task setProgressBlock:self.multiPartProgressBlock];
          [task setCompletionHandler:self.mutipartCompleteBlock];
    //            [task resume];
        }
    }
}];
this is i getMultiPartUploadTasks ,

**Comment by ruiguoamz** [comment] 2020-09-28 14:31
Hi, @Guolanlan 
Thanks for reaching out. 

First thing first, please avoid using languages other than English, otherwise, it makes us harder to help you. Thanks. 

I have edited you second comment to turn Chinese words to English words.

**Comment by Guolanlan** [comment] 2020-10-09 08:38
This problem is actually due to restarting the app, and the last saved sandbox path is not found. Using [NSHomeDirectory() stringByAppendingFormat:@"/Documents/%@.mp4] in this way, the file cannot be found.

**Comment by Guolanlan** [comment] 2020-10-09 08:48
AWS saves the absolute path

**Comment by taliwolk** [comment] 2021-04-21 12:28
Hi,
Is there any update regarding this issue? I'm encountering the same problem.
Multipart uploads will not reliably resume after app restart, because the app home directory sometimes change. (and always changes when launching from xcode).

Would appreciate any update,
Thanks!

**Comment by palpatim** [comment] 2021-04-22 16:19
Duplicate of https://github.com/aws-amplify/aws-sdk-ios/issues/1697

**Closed by palpatim** 2021-04-22 16:19 UTC
Labels: s3

**Comment by 353243186** [comment] 2021-04-25 10:27
Hi,
I have the same problem. Have you solved it?

**Comment by 353243186** [comment] 2021-04-26 08:20
> Hi,
> Is there any update regarding this issue? I'm encountering the same problem.
> Multipart uploads will not reliably resume after app restart, because the app home directory sometimes change. (and always changes when launching from xcode).
> 
> Would appreciate any update,
> Thanks!

Hello!
I have the same problem. Have you solved it?

**Comment by taliwolk** [comment] 2021-04-26 13:38
> Hello!
> I have the same problem. Have you solved it?

Hi there,
My solution was to save the relative path to the transfer utility DB instead of the full path.

For that purpose I have added the following helper functions to file **AWSS3TransferUtilityDatabaseHelper.m**

```
+ (NSString*)fullPathFromPath:(NSString*)relativePath
{
    return [NSHomeDirectory() stringByAppendingPathComponent:relativePath];
}

+ (NSString*)relativePathFromPath:(NSString*)fullPath
{
    return [fullPath stringByReplacingOccurrencesOfString:NSHomeDirectory() withString:@""];
}
```
And I'm using them when saving the file to the DB:

In function **insertTransferRequestInDB**, change line:
`@"file": file,`
to:
`@"file": [AWSS3TransferUtilityDatabaseHelper relativePathFromPath:file],`

And when reading it back from the DB, in function **getTransferTaskDataFromDB**, change line:
`[transfer setObject:[rs stringForColumn:@"file"] forKey:@"file"];`
to:
`[transfer setObject:[AWSS3TransferUtilityDatabaseHelper fullPathFromPath:[rs stringForColumn:@"file"]] forKey:@"file"];`

I have done some initial testing and I think it fixes the issue.
I hope I'm not missing something.

**Comment by 353243186** [comment] 2021-04-27 07:53
> > Hello!
> > I have the same problem. Have you solved it?
> 
> Hi there,
> My solution was to save the relative path to the transfer utility DB instead of the full path.
> 
> For that purpose I have added the following helper functions to file **AWSS3TransferUtilityDatabaseHelper.m**
> 
> ```
> + (NSString*)fullPathFromPath:(NSString*)relativePath
> {
>     if (relativePath.length == 0) {
>         return  relativePath;
>     }
>     return [NSHomeDirectory() stringByAppendingPathComponent:relativePath];
> }
> 
> + (NSString*)relativePathFromPath:(NSString*)fullPath
> {
>     return [fullPath stringByReplacingOccurrencesOfString:NSHomeDirectory() withString:@""];
> }
> ```
> 
> And I'm using them when saving the file to the DB:
> 
> In function **insertTransferRequestInDB**, change line:
> `@"file": file,`
> to:
> `@"file": [AWSS3TransferUtilityDatabaseHelper relativePathFromPath:file],`
> 
> And when reading it back from the DB, in function **getTransferTaskDataFromDB**, change line:
> `[transfer setObject:[rs stringForColumn:@"file"] forKey:@"file"];`
> to:
> `[transfer setObject:[AWSS3TransferUtilityDatabaseHelper fullPathFromPath:[rs stringForColumn:@"file"]] forKey:@"file"];`
> 
> I have done some initial testing and I think it fixes the issue.
> I hope I'm not missing something.

There is no problem with this solution. But I have another problem. As you know, the task status is  because they reconstructed the slice upload task (the absolute address was used during the reconstruction process). They did not resume the previous upload progress before restarting, but started from the beginning, which means that they did not resume the upload at a breakpoint.

**Comment by 353243186** [comment] 2021-04-27 07:59
> Hi,
> Is there any update regarding this issue? I'm encountering the same problem.
> Multipart uploads will not reliably resume after app restart, because the app home directory sometimes change. (and always changes when launching from xcode).
> 
> Would appreciate any update,
> Thanks!

May I add your contact information? I am a developer from China。
