### ISSUE TITLE
Support for tvOS

### ISSUE THREAD

**Issue by abdelrahman-ahmed** [aws-amplify/aws-sdk-ios#2376] opened 2020-03-22 12:41 UTC
**Additional context**
we are using amazon services for our system but the system is working on 7 platforms. unfortulanlty  I AWS sDk doesn't support tvOS which is very important to our users, If you will not support tvOS  in the near feature we may switch from amazon products to alternative services.

**Comment by palpatim** [comment] 2020-10-15 20:21
Dupe of https://github.com/aws-amplify/aws-sdk-ios/issues/1078

**Closed by palpatim** 2020-10-15 20:21 UTC
Labels: feature-request, tvOS
