### ISSUE TITLE
Use carthage to update to version 2.7.3 gives error on building

### ISSUE THREAD

**Issue by nourahassan** [aws-amplify/aws-sdk-ios#1129] opened 2018-11-28 19:31 UTC
When doing `carthage update`, I got version `2.7.3`. Carthage built successfully but when run the app on Xcode, at strip frameworks phase I got next error:
 
```
Code Signing ./AWSMobileClient.framework/AWSMobileClient with Identity -
/usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements ./AWSMobileClient.framework/AWSMobileClient
./AWSMobileClient.framework/AWSMobileClient: replacing existing signature
fatal error: lipo: -remove's specified would result in an empty fat file
Command PhaseScriptExecution failed with a nonzero exit code
```

 - SDK Version: 2.7.3
 - Dependency Manager: Carthage
 - Swift Version : 4.2.1
- Xcode 10.1

**Comment by nourahassan** [comment] 2018-11-28 19:43
Same with `2.7.0` too. Here's the cartfile:

```
github "nschum/SwiftHamcrest"
github "awslabs/aws-mobile-appsync-sdk-ios"
github "aws/aws-sdk-ios" == 2.7.0
```

Resolved to this:

```
github "ashleymills/Reachability.swift" "v4.3.0"
github "aws/aws-sdk-ios" "2.7.0"
github "awslabs/aws-mobile-appsync-sdk-ios" "2.7.0"
github "nschum/SwiftHamcrest" "2.1.0"
github "stephencelis/SQLite.swift" "0.11.5"
```

**Comment by rohandubal** [comment] 2018-12-03 21:57
Hello @nourahassan 

Sorry you are having trouble using the SDK. 

Could you please build the Carthage dependencies using `--no-use-binaries` and see if the issue still happens for you? I will also try to reproduce this on my side in the meanwhile.

Thanks,
Rohan

**Comment by rohandubal** [comment] 2018-12-03 22:34
I tried to re-produce this issue on my side but was un-able to. Could you please provide a  minimal sample project where we could debug this?

**Comment by nourahassan** [comment] 2018-12-04 19:44
I used the flag and get same error. 
I am building with Xcode 10.1 and simulator iPhone X which has iOS 12.1

I will try to make a sample project on the weekend.

**Comment by rohandubal** [comment] 2018-12-04 22:57
Thanks @nourahassan. Appreciate the effort!

**Comment by Atticus08** [comment] 2018-12-10 16:33
I've been getting this issue ever since I moved to v2.7.* as well. @nourahassan have you been able to make any progress on this? I've reverted back to the last revision in v2.6, but I'd really like to start using some of the newer features implemented in 2.7

**Comment by nourahassan** [comment] 2018-12-10 18:00
> I've been getting this issue ever since I moved to v2.7.* as well. @nourahassan have you been able to make any progress on this? I've reverted back to the last revision in v2.6, but I'd really like to start using some of the newer features implemented in 2.7

I am also using last version on 2.6. I will try and attach a sample project with the error to the ticket so they can fix it (if they cannot reproduce).

**Comment by rohandubal** [comment] 2018-12-11 22:19
Hello @nourahassan @Atticus08 

With release `2.7.4` we updated our release to include binaries built with Xcode 10.1.0 and latest Swift version. Could you please confirm if this works for you?

Thanks
Rohan

**Comment by Atticus08** [comment] 2018-12-11 22:36
Hi @rohandubal ,

Release 2.7.4 seems to work for me for the most recent version of Xcode now. I should have mentioned that I was on the same version as @nourahassan  earlier. Thank you!

**Comment by muellerfr** [comment] 2018-12-11 22:43
@Atticus08, thank you confirming! I am going ahead and closing the issue.

**Closed by muellerfr** 2018-12-11 22:43 UTC
Labels: Core, requesting feedback

**Comment by muellerfr** [comment] 2018-12-12 00:04
@nourahassan - Awesome!
