### ISSUE TITLE
Where can I find the example code and help document for AWSPinpoint?

### ISSUE THREAD

**Issue by linjiework** [aws-amplify/aws-sdk-ios#4928] opened 2023-08-24 09:45 UTC
I only can find the API reference from url https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSPinpoint/.
I don't know how to use these API, and how to configure my iOS APP.
Where can I find the example code and help document for AWSPinpoint? Thanks!

**Comment by ruisebas** [comment] 2023-08-24 14:25
Hi @linjiework! The documentation for the AWS SDK for iOS is available [here](https://docs.amplify.aws/sdk/q/platform/ios/).
`AWSPinpoint` in particular is used for both [**Analytics**](https://docs.amplify.aws/sdk/analytics/getting-started/q/platform/ios/) and [**Push Notifications**](https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios/), where you can find setup instructions according to your use case.

In case you're developing a new app and looking to integrate with AWS, we advice you to check the [Amplify Library for Swift](https://github.com/aws-amplify/amplify-swift). This library automatically integrates with AWS and provides easy-to-use interfaces, Pinpoint being supported for Analytics and Push Notifications as well.

**Comment by linjiework** [comment] 2023-08-27 00:53
hank you!

There are some amplify command need to be run from my app project folder. (For example:  need to run command:'amplify notifications console', which in the webpage https://docs.amplify.aws/sdk/push-notifications/messaging-campaign/q/platform/ios/). But my app project doesn't add the Amplify Library,   Do I need to do this? Is this useful for my app project?
If these amplify commands are uesless for my app project, how should I configure for my iOS APP?

I try to add the code according to the document(no run amplify commands in my app project), and test it. App can get device token, and update success. But when I try to send message to this device in the Test messaging webpage of AWS Pinpoint. I get the error:’Internal Server Error’. I don't know where the problem occurred. 


Request body:
{"OptOut":"NONE","ChannelType":"APNS_SANDBOX","Metrics":{},"EffectiveDate":"2023-08-27T00:31:48.253Z","Address":"dd6ac71fc55306e39d2cf2065de28e40a6c57dd1661b169c0cf9ba6bff7e1815","Demographic":{"Locale":"zh_CN","Timezone":"Asia\/Shanghai","PlatformVersion":"15.4","AppVersion":"1.0","Model":"iPhone","Make":"apple","Platform":"iOS"},"Location":{},"Attributes":{},"User":{"UserAttributes":{}}}

Response body:
{"RequestID":"6408dc93-39dd-434b-a688-c09b6313d4b9","Message":"Accepted"}
2023-08-27 08:31:51:306 MouseTrap[6010:604884] Endpoint Updated Successfully! <AWSPinpointTargetingUpdateEndpointResponse: 0x28215c330> {
    messageBody = "<AWSPinpointTargetingMessageBody: 0x28237cb20> {\n    message = Accepted;\n    requestID = \"6408dc93-39dd-434b-a688-c09b6313d4b9\";\n}";

Error Message:
![error_detail](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/a81df092-452a-4f1c-8502-0f1b156aff56)

Send Message:
![error](https://github.com/aws-amplify/aws-sdk-ios/assets/53046626/6e47bb5f-fe99-44e6-b39b-4424852a8ae1)





BTW: The Amplify Library  doesn't support the AWS DynamoDB and the AWS Lambda, so I have to use the aws-sdk-ios.  After the aws-sdk-ios has been added in my project, I can not add the Amplify Library in this project. I can add the aws-android-sdk and the Amplify Library in my Android project, but can not to do so in my iOS project. So I have to research how to use the AWSPinpoint.

**Comment by linjiework** [comment] 2023-08-28 00:00
I have an Android APP, it supports AWSPinpoint, and I set the configure of iOS APP the same with the configure of this Android APP.

**Comment by ruisebas** [comment] 2023-08-28 19:27
Most of the `amplify` commands allow you to easily set up your backend resources and/or connect them to your application. It's fine to not run them if you are using your existing AWS resources.

Unfortunately the error you are seeing in the console comes directly from the Pinpoint Service, so I don't know what exactly could be causing it or what went wrong.
The [API documentation](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-messages.html) only states that:
> TEMPORARY_FAILURE – A temporary error occurred. Amazon Pinpoint won't attempt to send the message again.

What you could do if confirm that:
- Your endpoint update requests are indeed hitting the right Pinpoint resource, i.e. that the Pinpoint AppId you are setting is the correct one.
- You can "see" the endpoint in the Pinpoint Console, either on the **Analytics** tab or by creating a new **Segment**  that should include it.
- That you've correctly configured the APNs integration with Pinpoint, using the proper certificates with the right values (e.g. bundle. id, team id, etc)

**Comment by linjiework** [comment] 2023-08-29 03:03
Thank you very much. The problem has solved, now the AWSPinpoint can work on my iOS APP.

**Comment by ruisebas** [comment] 2023-08-29 14:20
That's great to hear! 
Out of curiosity, did you find out what was the root cause? Or was it a transient issue in the Pinpoint service?

**Comment by linjiework** [comment] 2023-08-30 08:31
It's my mistake. I selected the wrong Certificate Type when building the certificates. When creating the new push notifications certificate In the Apple Certificates, Identifiers & Profiles web page,  should select 'Apple Push Notification service SSL (Sandbox)', not 'Apple Push Notification service SSL (Sandbox & Production)'.

**Comment by ruisebas** [comment] 2023-08-30 14:11
🤔 Hmm that's weird, **Apple Push Notification service SSL (Sandbox & Production)** should be the one that works. There was probably something else wrong on the old certificate.

Keep in mind that it's probably a bad idea to use the Sandbox environment on a Prod app, so you might wanna change that before you release your app.

Closing this issue, as it was resolved. Thanks!

**Closed by ruisebas** 2023-08-30 14:11 UTC
Labels: question, pinpoint
