### ISSUE TITLE
AWSCredentials of DeveloperAuthenticatedIdentityProvider are not being cached

### ISSUE THREAD

**Issue by phanchutoan** [aws-amplify/aws-sdk-ios#1554] opened 2019-05-17 08:46 UTC
**Describe the bug**
AWSCredentials of DeveloperAuthenticatedIdentityProvider seems not being cached, this make creating multiple pre-signed urls run slow on app second start

**To Reproduce**

Using Developer Authenticated Identity Provider
```
DeveloperAuthenticatedIdentityProvider * devAuth = [[DeveloperAuthenticatedIdentityProvider alloc] initWithRegionType:AWSRegionAPNortheast1
                                                                                                           identityPoolId:@"xxxxxx"
                                                                                                          useEnhancedFlow:YES
                                                                                                  identityProviderManager:nil];
    
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]
                                                      initWithRegionType:AWSRegionAPNortheast1
                                                      identityProvider:devAuth];


AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionAPNortheast1 credentialsProvider:credentialsProvider];

AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

Get pre-signed urls in a loop

```
NSLog(@"i=0: %@", [NSDate date]);
NSString *bucket = @"example.com";
for (int i=0; i < 1000; i++) {
    NSString *key = [NSString stringWithFormat:@"testkey%d", i];
    AWSS3GetPreSignedURLRequest *getPreSignedURLRequest = [AWSS3GetPreSignedURLRequest new];
    getPreSignedURLRequest.bucket = bucket;
    getPreSignedURLRequest.key = key;
    getPreSignedURLRequest.expires = [NSDate dateWithTimeIntervalSinceNow:3600];
    getPreSignedURLRequest.HTTPMethod = AWSHTTPMethodGET;
    [[[AWSS3PreSignedURLBuilder defaultS3PreSignedURLBuilder] getPreSignedURL:getPreSignedURLRequest]
     continueWithBlock:^id(AWSTask *task) {
         if (task.error) {
             NSLog(@"Error: %@",task.error);
         } else {
             NSURL *presignedURL = task.result;
             NSLog(@"presignedURL: \n%@", presignedURL);
         }
         if (i == 999) {
             NSLog(@"i=999: %@", [NSDate date]);
         }
         return nil;
     }];
}
```
**Which AWS service(s) are affected?**
AWSCore, AWSS3

**Behavior**

On app first start, it takes only 1 second for 1000 getPresignUrl request
On app second startup, it takes about 2 minutes for 1000 getPresignUrl request

-----------------------
I have taken a look at the sdk source code and i found this

File path: /Pods/AWSCore/AWSCore/Authentication/AWSCredentialsProvider.m - Line 699
```
- (AWSCredentials *)internalCredentials {
   if (_internalCredentials) {
       return _internalCredentials;
   }

   if (self.keychain[AWSCredentialsProviderKeychainAccessKeyId]
       && self.keychain[AWSCredentialsProviderKeychainSecretAccessKey]) {
       NSString *expirationString = self.keychain[AWSCredentialsProviderKeychainExpiration];
       NSDate *expiration = nil;
       if (expirationString) {
           expiration = [NSDate dateWithTimeIntervalSince1970:[expirationString doubleValue]];
       }
       AWSCredentials *credentials = [[AWSCredentials alloc] initWithAccessKey:self.keychain[AWSCredentialsProviderKeychainAccessKeyId]
                                                                     secretKey:self.keychain[AWSCredentialsProviderKeychainSecretAccessKey]
                                                                    sessionKey:self.keychain[AWSCredentialsProviderKeychainSessionToken]
                                                                    expiration:expiration];
       return credentials;
   }

   return nil;
}
```

_internalCredentials seem to be the cache for the AWSCredentials. It check the cache first, if it not exist, it will create new AWSCredentials. 

The problem here is it do not save the AWSCredentials cache after create it. 
When app start at first time the cache may have been created and saved in some way, but on second time the SDK create new AWSCredentials for each pre-signed url request and this make the pre-sign url creation very slow.

If I change the source code to this, getPresignUrlsRequest run fast every time.

```
- (AWSCredentials *)internalCredentials {
   if (_internalCredentials) {
       return _internalCredentials;
   }

   if (self.keychain[AWSCredentialsProviderKeychainAccessKeyId]
       && self.keychain[AWSCredentialsProviderKeychainSecretAccessKey]) {
       NSString *expirationString = self.keychain[AWSCredentialsProviderKeychainExpiration];
       NSDate *expiration = nil;
       if (expirationString) {
           expiration = [NSDate dateWithTimeIntervalSince1970:[expirationString doubleValue]];
       }
       AWSCredentials *credentials = [[AWSCredentials alloc] initWithAccessKey:self.keychain[AWSCredentialsProviderKeychainAccessKeyId]
                                                                     secretKey:self.keychain[AWSCredentialsProviderKeychainSecretAccessKey]
                                                                    sessionKey:self.keychain[AWSCredentialsProviderKeychainSessionToken]
                                                                    expiration:expiration];

       //Cache the credentials here
       _internalCredentials = credentials;
       return credentials;
   }

   return nil;
}
```

I am not sure if this is a bug or just my wrong implementation. Appreciate any help.
Thank you.

**Comment by rohandubal** [comment] 2019-05-19 00:21
Hello @phanchutoan 

Could you please specify that in the 2nd run of the app, is it only the 1st URL which takes long time and sub-sequent ones are faster? or is it that all URLs take time?

Thanks,
Rohan

**Comment by phanchutoan** [comment] 2019-05-19 00:42
@rohandubal all the urls take time to be create. But if I wait for about 30 minutes. An start the app again. I create all the urls very fast. And it become slow again right after I restart the app.

**Comment by palpatim** [comment] 2019-07-17 18:02
@phanchutoan Thanks for the explanation. I agree that setting the local in-memory variable to the value stored in the keychain makes sense, if we're retrieving the value from the keychain anyway. We'll put this on our backlog to fix.

---

**Implementation Notes**

- Update both `-[AWSCognitoCredentialsProvider internalCredentials]` and `-[AWSWebIdentityCredentialsProvider internalCredentials]` to have the same behavior
- Add unit tests to assert the correct behavior in both classes

**Comment by phanchutoan** [comment] 2019-07-23 23:57
Hi @palpatim 
Thank you 

I just tried your fix, it seem that 'internalCredentials' is being retrieved from keychain successfully.
But the internalCredential will die after 1 or 2 hours, I am not sure.
```
    if (self.keychain[AWSCredentialsProviderKeychainAccessKeyId]
        && self.keychain[AWSCredentialsProviderKeychainSecretAccessKey]) {
        NSString *expirationString = self.keychain[AWSCredentialsProviderKeychainExpiration];
        NSDate *expiration = nil;
        if (expirationString) {
            expiration = [NSDate dateWithTimeIntervalSince1970:[expirationString doubleValue]];
        }
        AWSCredentials *credentials = [[AWSCredentials alloc] initWithAccessKey:self.keychain[AWSCredentialsProviderKeychainAccessKeyId]
                                                                      secretKey:self.keychain[AWSCredentialsProviderKeychainSecretAccessKey]
                                                                     sessionKey:self.keychain[AWSCredentialsProviderKeychainSessionToken]
                                                                     expiration:expiration];
        _internalCredentials = credentials;
        return credentials;
    }
```
The `self.keychain[AWSCredentialsProviderKeychainExpiration];` seem to expire after 1 or 2 hours. May be it need to be renew some where.

**Comment by palpatim** [comment] 2019-09-05 15:18
Regarding the original issue of slow presigned URL generation on app restart: #1678 does appear to fix the issue, and we have a fix pending the next release. No firm ETA on it, but we're actively working on resolving the last blocking issues.

Regarding the second issue of expiring credentials--this is expected behavior. The system would require a credential refresh before proceeding. In the discussion of https://github.com/aws-amplify/aws-sdk-ios/issues/1691#issuecomment-528079946, I point out that a workaround for this is to ensure credentials are refreshed prior to beginning a batch operation. That would cause the cached and in-memory credentials to be refreshed and available, and would also greatly improve performance since the batched presignURL operations would not be contending for resources while the credentials refresh is happening.

**Comment by palpatim** [comment] 2019-09-10 13:56
We released the fix for this in https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

Thanks for the callout and the initial suggestion!

**Comment by phanchutoan** [comment] 2019-09-17 07:18
Thanks you @palpatim. It seem working fine now after update.

**Closed** 2019-09-17 07:18 UTC
Labels: Bug, Cognito
