### ISSUE TITLE
AWSS3TransferManager Deprecation

### ISSUE THREAD

**Issue by nick3389** [aws-amplify/aws-sdk-ios#3136] opened 2020-10-19 13:41 UTC
**State your question**
Based on the 2.18.0 release notes, `AWSS3TransferManager` will be deprecated on December 2020. You suggest to switch to Amplify storage for uploads and downloads to S3. Is `AWSS3TransferUtility` going to be deprecated too? AmplifyStorage does not support uploads and downloads while the app is in the background and that's why we haven't switched to Amplify yet. Another reason is that Amplify does not support the `AWSStaticCredentialsProvider` with static credentials for S3 upload/download (I know that it's not recommended but that's the setup we use now for various reasons).

I have raised a similar question in the Amplify repo. You can check it [here](https://github.com/aws-amplify/amplify-ios/issues/638).

**EDIT**
I just noticed that the deprecation message of `AWSS3TransferManager` states to use `AWSS3TransferUtility` for uploading/downloading files, so I guess we are ok...

**Comment by palpatim** [comment] 2020-10-19 14:21
@nick3389 Sorry for the confusion.

AWSS3TransferManager is already deprecated (we did so back in 2018), but we're removing the client altogether in December. Amplify Storage should be used for all new applications. For existing applications, we recommend you evaluate migration to the Amplify libraries. The AWS Mobile SDK (including TransferUtility) will continue be maintained with bug fixes and security updates.

For what it's worth, Amplify Storage does support background uploads and downloads (in fact currently Amplify Storage uses TransferUtility under the covers (but don't rely on that because it's an implementation detail that may change)). However, you're correct that we don't offer an easy way to deal with static credentials, so if TransferUtility is the right solution for your use case, you can continue to use it.

**Comment by nick3389** [comment] 2020-10-19 14:29
@palpatim Thank you for your reply. However, do you intend to implement a static credentials approach?

**Comment by palpatim** [comment] 2020-10-19 14:40
We don't have anything currently on the (or even a feature request that I'm aware of) for static credentials in Amplify. The main use case I'm aware of for static credentials is to handle long-lived presigned URLs for uploads and downloads. Do you have other use cases? That would help inform our thinking about this.

**Comment by nick3389** [comment] 2020-10-19 14:54
That's exactly my case. We use static credentials so as to not have to create pre-signed urls like we did with Cognito some years ago. Actually our setup is to create a service configuration instance with static credentials to be able to upload to S3 even in the background. The files are not large but instant upload is of essence.

**Comment by palpatim** [comment] 2020-10-19 16:01
Thanks for the feedback. I am going to open a feature request for supporting long-running background operations in Amplify Storage, which I think encapsulates the use case correctly, and we'll see what the best way to enable that is.

**Comment by palpatim** [comment] 2020-11-08 16:36
I've re-titled @nick3389's issue https://github.com/aws-amplify/amplify-ios/issues/638 to more accurately reflect the use case of supporting long-running background operations. Static credentials may be a way (and indeed may be the *only* way) to accomplish the use case, but we don't want the investigation of the feature to center around that before exploring other options.

I'm closing this issue as a dupe of https://github.com/aws-amplify/amplify-ios/issues/638.

**Closed** 2020-11-08 16:36 UTC
Labels: duplicate, question, s3
