### ISSUE TITLE
AWSIoT Attach Policy method call gives unsupported URL error

### ISSUE THREAD

**Issue by vishal-android-freak** [aws-amplify/aws-sdk-ios#2403] opened 2020-04-02 16:52 UTC
AWSIoT Attach Policy method call gives unsupported URL error

here is my code

```swift
let attachPolicyReq = AWSIoTAttachPolicyRequest()
        attachPolicyReq!.policyName = policyName
        attachPolicyReq!.target = AWSMobileClient.default().identityId
        AWSIoT(forKey: "IoTConfig").attachPolicy(attachPolicyReq!)
            .continueWith(block: {
                (task) -> AnyObject? in
                if let error = task.error {
                    DispatchQueue.main.async {
                        result(FlutterError(code: "Error", message: "Error attaching policy", details: error.localizedDescription))
                    }
                }
                DispatchQueue.main.async {
                    result(true)
                }
                return nil
            })
```

I get the following error

```
Task <2245AFF5-B594-43CB-93C1-7C4573C85970>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=<my-key>-ats.iot.us-west-2.amazonaws.com/target-policies/iot-test,
```

I am testing my app on an iPad Pro latest version running iOS 13.4.

I have masked the key <my-key> here but the URL is proper in my actual code.

**Comment by palpatim** [comment] 2020-04-03 16:49
Does the URL in the error message include the `https` scheme, or is it truly just begin with the bare hostname?

**Comment by vishal-android-freak** [comment] 2020-04-03 17:49
It begins with the bare hostname, no https in the beginning.

**Comment by vishal-android-freak** [comment] 2020-04-03 18:52
https://agnostech.github.io/flutteramplify/#/

I am building this. PubSub package is almost ready too. Android part is ready, I am stuck on iOS because of this issue. Help would be appreciated. If you can guide me to the place where https is not getting appended, I can send a PR :)

**Comment by vishal-android-freak** [comment] 2020-04-05 19:34
Any update on this?

**Comment by vishal-android-freak** [comment] 2020-04-16 13:53
Hey, can anyone please comment on this issue?

**Comment by lawmicha** [comment] 2020-04-16 15:58
Hi @vishal-android-freak I took a look at the sample here https://github.com/awslabs/aws-sdk-ios-samples/tree/master/IoT-Sample/Swift

and there is a constant for the endpoint in the format of 
`let IOT_ENDPOINT = "https://xxxxxxxxxx.iot.<region>.amazonaws.com"`

It gets used when configuring the AWSIoTDataManager
```
// IoT Dataplane must use your account specific IoT endpoint
        let iotEndPoint = AWSEndpoint(urlString: IOT_ENDPOINT)
        
        // Configuration for AWSIoT data plane APIs
        let iotDataConfiguration = AWSServiceConfiguration(region: AWS_REGION,
                                                           endpoint: iotEndPoint,
                                                           credentialsProvider: credentialsProvider)
        //IoTData manager operates on xxxxxxx-iot.<region>.amazonaws.com
        AWSIoTDataManager.register(with: iotDataConfiguration!, forKey: AWS_IOT_DATA_MANAGER_KEY)
```

With the sample app, i am able to connect to the MQTT websocket. I haven't tested the attach policy call yet, but want to clarify the set up on your end

How are you configuring the IoT instance and what does your configuration values look like?
Is the static endpoint in your config already contains "https://" at the beginning? 
Are you able to make any other calls in the SDK?

**Comment by vishal-android-freak** [comment] 2020-04-16 17:30
YES! It needed `https`. Android doesn't require https in its configuration. :/

But now I have another error
The error says `not found`.

But the policy exists by the name that's mentioned in the code.

@lawmicha any clue about this?

**Comment by lawmicha** [comment] 2020-04-16 18:43
Hi @vishal-android-freak , glad you were able to resolve the problem. That does seem odd that Android does not require https in its configuration. Although they should be functionally the same, it appears on iOS, the configuration uses `AWSEndpoint` while Android uses the `AWSIotMqttManager` class, which is why they differ.

iOS https://aws-amplify.github.io/docs/sdk/ios/pubsub
Android https://aws-amplify.github.io/docs/sdk/android/pubsub

Hopefully this issue captures a painpoint that another developer may run into and this will help resolve it. I'm going to close this this since the original question is answered. 

To your follow up, feel free to open another issue with more clarification such 
- How do I reproduce this? How was the policy created, what type of `identity` is the target?
- Does this call work when using AWS CLI? ie. https://docs.aws.amazon.com/cli/latest/reference/iot/attach-policy.html
- Any more verbose error message or stack trace?
- Any additional context about the use case you are trying to achieve.

**Closed by lawmicha** 2020-04-16 18:43 UTC
Labels: IoT, Requesting Feedback, bug
