### ISSUE TITLE
macCatalyst support

### ISSUE THREAD

**Issue by Cyclic** [aws-amplify/aws-sdk-ios#2536] opened 2020-05-03 04:48 UTC
**Describe the bug**
When compiling for Mac, it would be great if the AWSCore compiled so that we get Mac Catalyst support. Instead we get the attached errors:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/553800/80898874-b44eeb80-8cbd-11ea-99aa-fcca5fdea9d4.png">

**To Reproduce**
1. Create a new SwiftUI project in Xcode and add the AWSS3 pod with the AWS SDK.
2. Check the Mac OS support in the general section of the project settings
3. Attempt to build

**Observed Behavior**
Error occurs during build.

**Expected Behavior**
There should be a successful build.

**Stack Trace**
<img width="2221" alt="image" src="https://user-images.githubusercontent.com/553800/80898900-f4ae6980-8cbd-11ea-8e3c-e34186001d56.png">

**Code Snippet**
```
+ (void)requestSharedWebCredentialForDomain:(NSString *)domain account:(NSString *)account completion:(void (^)(NSArray UIC_CREDENTIAL_TYPE *credentials, NSError *error))completion
{
    SecRequestSharedWebCredential((__bridge CFStringRef)domain, (__bridge CFStringRef)account, ^(CFArrayRef credentials, CFErrorRef error) {
        if (error) {
            NSError *e = (__bridge NSError *)error;
            if (e.code != errSecItemNotFound) {
                NSLog(@"error: [%@] %@", @(e.code), e.localizedDescription);
            }
        }
        
        NSMutableArray *sharedCredentials = [[NSMutableArray alloc] init];
        for (NSDictionary *credential in (__bridge NSArray *)credentials) {
            NSMutableDictionary *sharedCredential = [[NSMutableDictionary alloc] init];
            NSString *server = credential[(__bridge __strong id)kSecAttrServer];
            if (server) {
                sharedCredential[@"server"] = server;
            }
            NSString *account = credential[(__bridge __strong id)kSecAttrAccount];
            if (account) {
                sharedCredential[@"account"] = account;
            }
            NSString *password = credential[(__bridge __strong id)kSecSharedPassword];
            if (password) {
                sharedCredential[@"password"] = password;
            }
            [sharedCredentials addObject:sharedCredential];
        }
        
        if (completion) {
            completion(sharedCredentials.copy, (__bridge NSError *)error);
        }
    });
}

+ (NSString *)generatePassword
{
    return CFBridgingRelease(SecCreateSharedWebCredentialPassword());
}
```

**Unique Configuration**
Standard configuration for everything from pods to Xcode Mac project with SwiftUI.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
  pod 'AWSS3'

**Screenshots**
See attached

**Environment(please complete the following information):**
 - SDK Version: latest
 - Dependency Manager: Cocoapods
 - Swift Version : latest
 - Xcode Version: latest

**Device Information (please complete the following information):**
 - iOS Version: latest
 - Mac OS: latest

**Additional context**
Basic upload app with S3 from example Amplify project should be sufficient to reproduce.

**Relevant Console Output**
```
'SecAddSharedWebCredential' is unavailable: not available on macCatalyst.
'SecRequestSharedWebCredential' is unavailable: not available on macCatalyst
'kSecSharedPassword' is unavailable: not available on macCatalyst
'SecCreateSharedWebCredentialPassword' is unavailable: not available on macCatalyst
```

**Comment by wcrtr** [comment] 2020-05-18 16:44
Having same issue. Would be great to get this resolved. As of now I'm going to have to look into a different solution because I want my app to be cross platform.

**Comment by Cyclic** [comment] 2020-05-24 06:40
@wcrtr I found that commenting out the lines in the cocoapod that had errors allowed me to build and run the app without any issues. S3 upload still worked. It's bit of a hack, but it's working for now and should be fine for a release.

**Comment by palpatim** [comment] 2020-05-27 14:42
Dupe of https://github.com/aws-amplify/aws-sdk-ios/issues/1603

**Closed by palpatim** 2020-05-27 14:42 UTC
