### ISSUE TITLE
Support Swift 4/4.1 for API Gateway Generated SDK

### ISSUE THREAD

**Issue by rainypixels** [aws-amplify/aws-sdk-ios#916] opened 2018-05-01 19:21 UTC
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
API Gateway.

* In what version of SDK are you facing the problem?
2.6.14.

* Is the issue limited to Simulators / Actual Devices?
Both.

* Can your problem be resolved if you bump to a higher version of SDK?
No actually.

* Is this problem related to specific iOS version?
Doesn't seem to be.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Carthage.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
It's the same issue as [this one](https://github.com/aws/aws-sdk-ios/issues/753). The developer who filed that issue closed it because of the workaround discussed in the comments but the generated SDK remains broken (see [comment](https://github.com/aws/aws-sdk-ios/issues/753#issuecomment-371453647)).

**Comment by rohandubal** [comment] 2018-05-01 20:17
Hello @rainypixels 

Currently the generated code is for Swift 3.2. To make it work with Swift 4/ Swift 4.1 you will have to mark the members of your model class with @objc / @objcmembers as specified [here](https://github.com/aws/aws-sdk-ios/issues/750#issuecomment-337046816).

I will mark this as an enhancement and update once we have support for Swift 4+

Thanks,
Rohan

**Comment by rainypixels** [comment] 2018-05-03 07:53
Thanks, @rohandubal! Do you have a rough ETA for when Swift 4/4.1 support is coming?

**Comment by rohandubal** [comment] 2018-05-04 18:36
I currently do not have a timeline/ ETA for this. I will try to get some information from the team and keep this Issue updated.

**Comment by VictorBuzz** [comment] 2018-05-10 05:32
Workaround from @rohandubal works, but I had to make one other change to make it work:

1. Go to **AWSMTLJSONAdapter.m** file.
2. Comment out line 150 to 153. It should look like:

```
        if (![propertyKeys containsObject:mappedPropertyKey]) {
            NSAssert(NO, @"%@ is not a property of %@.", mappedPropertyKey, modelClass);
            return nil;
        }
```

There's a problem with this validation, could be that it's checking the string object and not the string value.

**Comment by anthonynovatsis** [comment] 2018-05-11 04:32
Also hitting this issue with Swift 4. The workaround mentioned in #753 was not sufficient as per above https://github.com/aws/aws-sdk-ios/issues/916#issuecomment-387956454. Any update on when the generated SDK will be fixed?

**Comment by rainypixels** [comment] 2018-06-18 00:43
Any update on this?

**Comment by tchamblee** [comment] 2018-09-01 15:03
This really needs to be fixed.  I can't tell you how annoying it is to have to modify my swift classes to add `@objc` to all the properties EVERY TIME the SDK is regenerated.

**Comment by shawngrona** [comment] 2018-09-10 18:51
+1

**Comment by sungjin0213** [comment] 2018-09-10 18:57
+1 Please let us know if you have any ETA on this since it's been 4 months from original response, and we have been continually have to investigate the issues caused by not having @objcMembers. 

Most of developers will be using Swift 4 and up, so I'm not sure why Swift 4 is not supported yet.

**Comment by rodrigoarias89** [comment] 2018-10-10 14:13
+1 Really no news on this yet?

**Comment by palpatim** [comment] 2018-11-05 16:20
Sorry for the delay on this folks. We're preparing a fix to add `@objcMembers` to generated model classes, which should fix this issue. I don't have an ETA just now, but I'll update this thread when it's deployed.

**Comment by palpatim** [comment] 2018-11-19 15:30
This has been deployed to production. Generated SDKs now have `@objcMembers` annotations on model classes.

To be clear, this is a change on the [AWS API Gateway service](https://console.aws.amazon.com/apigateway/home), not the SDK. That means that you will need to re-generate your SDK.

Please let us know if you have any problems.

**Closed by palpatim** 2018-11-19 15:30 UTC
Labels: APIGateway, feature request, pending
