### ISSUE TITLE
Crash: AWSMobileClient $ss12_ArrayBufferV20_consumeAndCreateNew14bufferIsUnique15minimumCapacity13growForAppendAByxGSb_SiSbtF15AWSMobileClient28FetchUserPoolTokensOperationC_Tg5

### ISSUE THREAD

**Issue by zhouhao27** [aws-amplify/aws-sdk-ios#4266] opened 2022-08-17 03:37 UTC
**Describe the bug**
> Crashed: com.apple.root.default-qos
SIGSEGV 0x0000aa3a3db49fd0
AWSMobileClient $ss12_ArrayBufferV20_consumeAndCreateNew14bufferIsUnique15minimumCapacity13growForAppendAByxGSb_SiSbtF15AWSMobileClient28FetchUserPoolTokensOperationC_Tg5

**To Reproduce**
It happens randomly.

**Observed Behavior**

**Stack Trace**
Please provide a stack trace if applicable e.g. a crash is occurring.
```
Crashed: com.apple.root.default-qos
0  libswiftCore.dylib             0x388c9c _swift_release_dealloc + 32
1  AWSMobileClient                0x2ce74 $ss12_ArrayBufferV20_consumeAndCreateNewAByxGyF15AWSMobileClient28FetchUserPoolTokensOperationC_Tg5 + 72
2  AWSMobileClient                0x2cd24 $s15AWSMobileClientAAC9getTokensyyyAA0D0VSg_s5Error_pSgtcFyycfU0_ + 256
3  AWSMobileClient                0x2ca94 $sIeg_IeyB_TR + 20
4  Foundation                     0x98998 __111+[__NSOperationInternalObserver _observeValueForKeyPath:ofObject:changeKind:oldValue:newValue:indexes:context:]_block_invoke_2 + 36
5  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
7  libdispatch.dylib              0x7798 _dispatch_queue_override_invoke + 792
8  libdispatch.dylib              0x15de0 _dispatch_root_queue_drain + 396
9  libdispatch.dylib              0x16608 _dispatch_worker_thread2 + 164
10 libsystem_pthread.dylib        0x10b8 _pthread_wqthread + 228
11 libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**

**Screenshots**

**Environment(please complete the following information):**

- SDK Version: 2.27.9
- Dependency Manager: Cocoapods
- Swift Version : 5.0
- Xcode Version: 13.2

**Device Information (please complete the following information):**
 - iPhone 11
 - 15.3.1

**Comment by zhouhao27** [comment] 2022-08-19 08:08
I found one issue in Xcode for AWS sdk. Not sure it's related to crash or not.

<img width="1428" alt="截屏2022-08-19 下午4 06 08" src="https://user-images.githubusercontent.com/8099731/185573978-7f077517-ddff-4c51-a407-8bba9005b4e3.png">

**Comment by zhouhao27** [comment] 2022-08-23 01:18
It happened quite frequently. Here is another instance:

```
Crashed: com.apple.root.default-qos
0  libswiftCore.dylib             0x3d8d48 _swift_release_dealloc + 32
1  AWSMobileClient                0x1a284 $ss12_ArrayBufferV20_consumeAndCreateNew14bufferIsUnique15minimumCapacity13growForAppendAByxGSb_SiSbtF15AWSMobileClient28FetchUserPoolTokensOperationC_Tg5 + 280
2  AWSMobileClient                0x2cfb4 $ss12_ArrayBufferV20_consumeAndCreateNewAByxGyF15AWSMobileClient28FetchUserPoolTokensOperationC_Tg5 + 60
3  AWSMobileClient                0x2ce68 $s15AWSMobileClientAAC9getTokensyyyAA0D0VSg_s5Error_pSgtcFyycfU0_ + 260
4  AWSMobileClient                0x2cbc8 $sIeg_IeyB_TR + 28
5  Foundation                     0x89744 __111+[__NSOperationInternalObserver _observeValueForKeyPath:ofObject:changeKind:oldValue:newValue:indexes:context:]_block_invoke_2 + 36
6  libdispatch.dylib              0x25cc _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x40f4 _dispatch_client_callout + 20
8  libdispatch.dylib              0x71e0 _dispatch_queue_override_invoke + 788
9  libdispatch.dylib              0x15b24 _dispatch_root_queue_drain + 396
10 libdispatch.dylib              0x16330 _dispatch_worker_thread2 + 164
11 libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
12 libsystem_pthread.dylib        0xb98 start_wqthread + 8
```

**Comment by royjit** [comment] 2022-09-02 15:31
Can you try with the latest SDK, we did some fix to handle crashes on getToken - https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.27.12

**Comment by zhouhao27** [comment] 2022-09-06 07:50
@royjit It still happened in `2.27.13`.

**Comment by royjit** [comment] 2022-09-06 20:51
I am guessing the issue might be due to multiple thread trying access the shared `NSHashTable`. Created this PR that might potentially fix the issue, will you be able to test this? https://github.com/aws-amplify/aws-sdk-ios/pull/4290

**Comment by royjit** [comment] 2022-09-16 19:02
The change was merged in, Please verify with the latest version of sdk if the issue is still reproducible.

**Closed** 2022-09-23 18:27 UTC
Labels: bug, pending-response, mobile client, closing soon
