### ISSUE TITLE
Question about Amazon Trust Services

### ISSUE THREAD

**Issue by gi-ba** [aws-amplify/aws-sdk-ios#3369] opened 2021-01-11 04:56 UTC
Hi AWS team,

We receive this email: 

```
Hello,
You are receiving this message because your account has been identified as having used Amazon Simple Storage Service (S3)
and/or Amazon CloudFront within the past 6 months. This message is a reminder of the upcoming migration of both services’
default certificates to Amazon Trust Services, which will begin March 23, 2021. To prepare for this migration, we recommend
that you confirm that your applications trust Amazon Trust Services as a Certificate Authority. If your client trust store does
not trust the Certificate Authority, it will report the TLS certificate as “untrusted” and may close the connection.
```

On iOS client, we are using these pods version which are kinda old:

```
pod 'AWSCore', '2.6.6'
pod 'AWSS3', '2.6.6'
```

I have a question that do we need to do anything with these libraries on iOS after receiving this email ? The system is working fine and we are not intended to update these libraries at the moment if it is not necessary. 

Regards,
Bao

**Comment by gi-ba** [comment] 2021-01-14 04:02
Hi @wooj2,

```
Yes we are still using the old AWS SDK.

**Comment by wooj2** [comment] 2021-01-15 23:50
Hi @gi-ba ,

We do not believe that your app will be impacted even though you are using an older version of the SDK.  I checked out version 2.6.6 of the SDK and did not observe that we bundled any certificates with this version.  The intended behavior of the SDK is that it leverages the certificates coming from the underlying operating system -- in this case, iOS.  If your application is bundling a certificate that is supplied by our SDK, please let us know.

I will be optimistically closing this issue, but feel free to re-open this ticket if you have any additional questions.

**Closed by wooj2** 2021-01-15 23:50 UTC
Labels: follow up, question, s3
