### ISSUE TITLE
Why isn't swift returning my 1:m model data

### ISSUE THREAD

**Issue by mickeysox** [aws-amplify/aws-sdk-ios#2401] opened 2020-04-02 09:45 UTC
I have a 1:m relationship, but when I query the User in swift to get all the associated posts, I am not getting back any posts.

Querying the data in aws brings me back 1:m as expected...

````
Schema:

type User @model {
  id: ID!
  fullName: String!
  emailAddress: String!
  posts: [Post] @connection(name: "UserPostConnection")
}

type Post @model {
  id: ID!
  text: String!
  user: User @connection(name: "UserPostConnection")
  createdAt: String
  updatedAt: String
}

Query:
query {
	getUser(id: "879db4f2-1dad-47b9-b70d-8bca15bf2549") {
	  id 
    posts {
      items {
        id
      }
    }
	}
}

Output:
{
  "data": {
    "getUser": {
      "id": "879db4f2-1dad-47b9-b70d-8bca15bf2549",
      "posts": {
        "items": [
          {
            "id": "04c4b571-6e92-4745-9a40-1a67a9d49d77"
          },
          {
            "id": "0f44fe6e-4e15-4a8c-b591-555e8fa1f60e"
          },
          {
            "id": "60c18c40-fea3-4ff3-8b21-df6857703dd2"
          }
        ]
      }
    }
  }
}
````
But running this in swift, doesn't bring back any posts?

````
        let queryInput = GetUserQuery(id: "879db4f2-1dad-47b9-b70d-8bca15bf2549")
        appSyncClient?.fetch(query: queryInput, cachePolicy: .fetchIgnoringCacheData) { (result, error) in
            print(result?.data?.getUser?.posts)
        }
````
````
output:
Optional(AWSStackSocial.GetUserQuery.Data.GetUser.Post(snapshot: ["__typename": Optional("ModelPostConnection"), "nextToken": nil]))
````

Whereas if I run this ListPosts I can see all the posts. As you can see from the grapql queries, the data is associated, so I am unsure what I am doing wrong? Or is this expected behaviour?

**Comment by palpatim** [comment] 2020-04-03 16:43
Dupe of https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/376

**Closed** 2020-04-03 16:44 UTC
Labels: AppSync, Duplicate

**Comment by mickeysox** [comment] 2020-04-03 17:10
> Dupe of [awslabs/aws-mobile-appsync-sdk-ios#376](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/376)

Yeah sorry about that, I'm struggling to get any answers.  Any idea?
