### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by shaneblandford** [aws-amplify/aws-sdk-ios#2395] opened 2020-03-30 16:46 UTC
**Describe the bug**
Upgraded to the new version of Xcode 11.4 project will not compile.

Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler: <full path removed>/Frameworks/AWSMobileClient.framework/Modules/AWSMobileClient.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**To Reproduce**

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.13.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device:  Simulator
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**
Looks like this issue was created with the March 24th release of XCode.

**Comment by AshrafJaddo** [comment] 2020-03-30 18:54
+1 for everyone who uses the binary frameworks instead of Carthage build which takes like an hour to build all frameworks.

**Comment by palpatim** [comment] 2020-04-03 16:27
Dupe of https://github.com/aws-amplify/aws-sdk-ios/issues/2365

**Closed by palpatim** 2020-04-03 16:27 UTC
