### ISSUE TITLE
AWSS3TransferUtility progressBlock cycle run and completionHandler is not calling 

### ISSUE THREAD

**Issue by AlexCzs** [aws-amplify/aws-sdk-ios#2245] opened 2020-01-20 05:34 UTC
upload video data, progressBlock will cycle running,progress value 0-1, when the progress= 1,completionHandler is not calling, and progressBlock will restart running from 0-1.
check the resouce code in AWSS3TransferUtility,the progressBlock invoked in -enumerateToAssignBlocksForUploadTask:downloadTask:,but -URLSession:task:didCompleteWithError: will never call.

Network node：Singapore
AWSRegionType: AWSRegionEUCentral1

    AWSS3TransferUtilityUploadExpression *expression = [[AWSS3TransferUtilityUploadExpression alloc] init];
    if (videoAttachId.length) {
        [expression setValue:videoAttachId forRequestHeader:@"x-amz-meta-video-attach-id"];
    }
    expression.progressBlock = ^(AWSS3TransferUtilityTask * _Nonnull task, NSProgress * _Nonnull progress) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (progressBlock) {
                progressBlock(progress.fractionCompleted,fileName);
            }
        });
    };
    
    AWSS3TransferUtilityUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityTask * _Nonnull task,NSError * _Nonnull error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            videoAttachId = nil;
            if (error) {
                NSLog(@"upload failed %@",error);
                NSString *errorMessage = [NSString stringWithFormat:@"%@", error.description];
                if (errorBlock) {
                    errorBlock(errorMessage);
                }
            } else {
                NSLog(@"upload success %@",task);
                if (successBlock) {
                    successBlock(fileName);
                }
            }
        });
    };
    
    NSString *contenType = [self dataContenTypeWithType:type];
    AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility S3TransferUtilityForKey:S3BucketName];
    [transferUtility uploadData:data
                         bucket:S3BucketName
                            key:fileName
                    contentType:contenType
                     expression:expression
              completionHandler:completionHandler];

 - AWS SDK Version: 2.12.3
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2
 - Device: iPhone8
 - iOS Version: iOS 12.3

**Comment by lawmicha** [comment] 2020-01-23 18:33
Hi @AlexCzs, thanks for reporting this issue. 

Is this happening for all uploads that the completion handler is not called?
If not, is there something special about this scenario when you run into the issue? 

You can enable more verbose debugging logs when you launch the app with 
```
AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

What logs do you see when this occurs?

**Comment by nick3389** [comment] 2020-02-13 10:32
@lawmicha  @AlexCzs I think this might be related to #2211

**Comment by nick3389** [comment] 2020-02-18 11:33
@lawmicha Same issue here. The issue seems to be resolved after a soft reset of the device, but I guess this is not a solution. I am guessing that the request is not even fired...

**Comment by palpatim** [comment] 2020-02-28 20:47
@AlexCzs @nick3389 

* Are you seeing the content upload successfully to S3 (e.g., by inspecting the target bucket in the S3 console), even though the callback is not invoked? Or is it the case that the upload does not complete?
* Do you have logging enabled? If not, please enable it (as @lawmicha suggested above) and let us know what you see.
* Does this happen only if the app is in the background, or also if it is in foreground? If only in background, are you intercepting background url events in `handleEventsForBackgroundURLSession`, as described in the [background transfer docs](https://aws-amplify.github.io/docs/sdk/ios/storage#background-transfers)?

In the meantime, I'm attempting to reproduce this issue with the S3 Transfer Utility [sample app](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferUtility-Sample).

**Comment by nick3389** [comment] 2020-02-28 20:54
@palpatim 

- No there is no content uploaded
- Logging is enabled but there nothing strange there. The last log after the creation of the task is something like `setting task identifier...`
- This happen both in foreground and background. Also, I handle the updates with `handleEventsForBackgroundURLSession`

Imagine that based on the implementation in the sample app you linked I see the following print and then nothing else. No call to the completion handler nor an uploaded file in S3.
`print("Upload Starting!")`

**Comment by palpatim** [comment] 2020-02-28 21:09
@nick3389 Thanks for the info. Does this happen more regularly on files of a particular size (e.g., very large or very small) or does it seem to happen irrespective of the size of the file being uploaded?

**Comment by nick3389** [comment] 2020-02-28 21:13
@palpatim I think it doesn't have to do with the size. It happened with 100kb files, 500kb & 3-4mb. I guess that for some reason(???) the upload does not even fire. I tried to intercept the requests of the app with a proxy like Charles to see if this is the case, but I thought to restart the phone first, should I had any luck. And since then, the issue has disappeared.

**Comment by palpatim** [comment] 2020-02-28 22:11
@nick3389 That behavior makes it sound like an in-process transfer was suspended/stuck by the OS or something. While I don't have any insight into how something like that could happen, I will say that the background transfer behaviors provided by iOS are opaque and largely out of the apps (or our) control. 

I'm unable to reproduce this issue in the sample app, although I do see `no background task exists with identifier` errors as others have reported both in our SDK and other SDKs. I'm continuing to look, but as it stands right now, I don't have any further insight into the behavior you saw in your case.

**Comment by nick3389** [comment] 2020-03-03 15:45
@palpatim I understand your point and probably something was (still is???) wrong with background tasks. Regarding the issue you mentioned for `no background task exists with identifier`, I haven't noticed something so far, but do you believe this might have to do with the issue I mentioned?

**Comment by palpatim** [comment] 2020-03-16 20:04
> Regarding the issue you mentioned for `no background task exists with identifier`, I haven't noticed something so far, but do you believe this might have to do with the issue I mentioned?

I haven't yet been able to draw any conclusions about that. The "no background task exists with identifier" message appears when moving from foreground to background, but does not seem to be related to tasks created by TransferUtility, since (at least in the sample app) the TU task eventually completes. I am continuing to investigate and will update if I have more info.

**Comment by nick3389** [comment] 2020-03-17 07:40
@palpatim Thank you for you answer. FYI, no issue so far, so I guess that something had to do with the OS... Anyway, if you discover something, let us know!

**Comment by palpatim** [comment] 2020-04-02 18:56
After investigating more, we don't see anything that would be causing sporadic errors. 

We do have some clarification about the original question: why does the progress handler get invoked multiple times without a callback being invoked.

What may be causing confusion is the system behavior behind the `timeoutIntervalForResource` configuration option. By default the `timeoutIntervalForRequest` and `timeoutIntervalForResource` values are 60 second and 3000 seconds respectively.

So in a poor network condition, if the upload task is not able to complete successfully in 60 seconds, the NSURLSession will retry the upload again. That's why the OP @AlexCzs sees the progress handler restarting.

This will continue for 3000 seconds, and only **after** that time, would you get an error response back on the callback.

If your use case is different and wanted to get the callback sooner, then you can manually setup the configuration and give a lower value for `timeoutIntervalForResource`:

```swift
let transferUtilityConfig = AWSS3TransferUtilityConfiguration()
transferUtilityConfig.timeoutIntervalForResource = 180

let configuration = AWSServiceConfiguration(region: .USEast1, credentialsProvider: AWSMobileClient.default())!

AWSS3TransferUtility.register(with: configuration, 
                        transferUtilityConfiguration: transferUtilityConfig, 
                      forKey: "test")
```

Bear in mind of course, that this adjusts the entire timeout, so it may not be appropriate to reduce this for very large files, since they might not be able to complete in the specified time period on slow networks.

Hope this helps. If you discover any other issues, please open a new ticket with details and we'll take a look.

**Comment by nick3389** [comment] 2020-05-14 11:05
@palpatim i confirm once again that I have not seen this error for a while now, so I believe that something was wrong in the system.

**Comment by royjit** [comment] 2020-06-04 19:57
Closing this issue since the error is no longer seen. Feel free to reopen if you face any issue.

**Closed by royjit** 2020-06-04 19:57 UTC
Labels: Requesting Feedback, S3, bug
