### ISSUE TITLE
Queueing many download task issue

### ISSUE THREAD

**Issue by rineek** [aws-amplify/aws-sdk-ios#1549] opened 2019-05-16 10:22 UTC
Fix introduced in version 2.9.1 is working for queueing many download tasks, but from version 2.9.3 it results in AWSCognitoCredentialsProviderCredentialsRefreshTimeout

Is there any particular reason that problem stated in #1188 and fix created in #1192 and deployed in version 2.9.1 was later overwritten in #1287 and deployed with version 2.9.3?

cc original author: @fer662

**Comment by rohandubal** [comment] 2019-05-19 00:10
Hello @rineek 

Thanks for bringing this to our attention, it seems like a miss from our side. We'll provide an update here once we get back the original fix.

Thanks,
Rohan

**Comment by fer662** [comment] 2019-05-20 17:04
@rineek The app that had problems is still running on my fork so I haven't hit the regression. Thanks for the heads up anyway! FWIW it's been running great.

**Comment by fer662** [comment] 2019-07-31 13:40
@rohandubal is the regression fixed? I'm having other issue I'm about to log, and I suppose one initial answer would be for me to update to latest, but I need to be sure I can.

**Comment by royjit** [comment] 2020-01-14 23:47
Hi @fer662 

Apologies for losing track of this.

Are you still facing this issue? Few related bugs were fixed in the latest iOS SDK, could you please check if the bug still exist?
https://github.com/aws-amplify/aws-sdk-ios/releases/2.11.0

**Comment by fer662** [comment] 2020-02-19 15:07
We're considering whether to update the sdk to the latest in case https://github.com/aws-amplify/aws-sdk-ios/issues/1707 gets resolved for us. We'll retest for this regression in that case.

**Comment by fer662** [comment] 2020-02-19 17:19
@royjit Queueing 200 requests feels pretty bad on 2.12.7 . I don't have time to analyze in depth right now but it seems that you're back to the inadequate thread control on the process of figuring out of a request has to issue a refresh. The whole figuring out must be synchronized as I explained in the original issue. The way it is, multiple requests can reach self.refreshingCredentials = YES; in  AWSCredentialsProvider.m before any of them get locked by the semaphore. Check my pull request from that issue.

**Comment by royjit** [comment] 2021-09-20 21:05
Are you still facing this issue? Wondering whether you have analyzed the root cause or got it fixed with the latest releases. I am putting this to closing soon, since there are no much activity in this thread.

**Closed** 2021-10-04 18:23 UTC
Labels: bug, core, cognito, closing soon
