### ISSUE TITLE
Get error while uploading a file on S3 bucket with latest release 2.37.1

### ISSUE THREAD

**Issue by VijayInnovana** [aws-amplify/aws-sdk-ios#5443] opened 2024-09-25 13:17 UTC
Getting error while uploading a file on S3 bucket with latest release 2.37.1
before this release working file, with the previous release 2.36.7 its working fine. After updating pods app getting this error :

Domain=com.amazonaws.AWSS3TransferUtilityErrorDomain Code=2 "Client Error" UserInfo={Server=AmazonS3, Transfer-Encoding=Identity, Connection=close, Content-Type=application/xml, Date=Wed, 25 Sep 2024 11:43:20 GMT, x-amz-request-id=1Y3CXQFS4V3V9E7R, NSLocalizedFailureReason=bad request, x-amz-id-2=6laFTPQe0JwIaqGf5RNozsa0VEzyuEpIj+OAlvZTDkVWqWraAa4klCl40p/mQUlYoC4M0L0TyIA=, HTTPStatusCode=400, NSLocalizedDescription=Client Error, x-amz-bucket-region=ap-south-1})

We used this function for uploading file on S3
"AWSS3TransferUtility.default().uploadData"

Please resolved this issue ASAP. My user base facing issue with file uploads on productions environments.

**Comment by ruisebas** [comment] 2024-09-25 13:24
Hi @VijayInnovana , thanks for reaching out.

There were no functionality changes made to the `AWSS3TransferUtility` between versions 2.36.7 and 2.37.1, so it's unclear why you're now getting an error.

To help us investigate further, please provide the following:
- The contents of your `awsconfiguration.json` file with sensitive information redacted.
- Verbose logs when you attempt to present the login view. You can enable verbose logging by doing this:
  ```swift
  AWSDDLog.sharedInstance.logLevel = .verbose
  AWSDDLog.sharedInstance.add(AWSDDOSLogger.sharedInstance)
  ```

**Comment by VijayInnovana** [comment] 2024-09-25 13:43
we use default configurations like this : 

let credentialsProvider = AWSStaticCredentialsProvider(accessKey: accessKey, secretKey: secretKey)
        let configuration = AWSServiceConfiguration(region: AWSRegionType.init(rawValue: AWSRegion.getRawValue(from: awsAccessRegion)) ?? .Unknown, credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
 After updating pods from 2.36.7 to 2.37.1 this issue occurs. when I am downgrade the pods from 2.37.1 to 2.36.7, then its working fine.

**Comment by ruisebas** [comment] 2024-09-25 14:05
Thanks, we'll take a look. But please provide the verbose logs as well.

**Comment by ruisebas** [comment] 2024-09-25 16:12
I replicated your setup and was still able to upload successfully calling 
`AWSS3TransferUtility.default().uploadData(_:bucket:key:contentType:expression:completionHandler:)`.

Some follow up questions:
- Which Xcode version are you using?
- Which iOS version are you building to?

Also, could you please share the full callsite to see what parameters you're including? Or alternatively, if you're able, a sample app project that reproduces the issue.

Thanks!

**Comment by VijayInnovana** [comment] 2024-09-26 05:08
Xcode version = version 16.0 (Current)
When we upload last app that have a issue, that time Xcode version 15.2
iOS Version = Any iOS version, not specific (iOS 17 or iOS 18)

When I am downgrade the pods from 2.37.1 to 2.36.7 without any app code changed, its working fine with latest Xcode and iOS version.

**Comment by VijayInnovana** [comment] 2024-09-30 13:39
Hi @ruisebas, 
Any update on this issue, because I not update latest pods of AWSS3 for iOS app with that issue.

**Comment by VijayInnovana** [comment] 2024-10-01 06:45
hi @ruisebas, 

Below added sample project and log files for both versions (2.37.2 and 2.36.7)

"AWS_2.36.7-Version_success_logs" this is successfully uploaded file on S3 server with 2.36.7 version.
"AWS_2.37.2-Version_error_logs" this is error log file while uploaded file on S3 server with 2.37.2 version.

[AWSSample.zip](https://github.com/user-attachments/files/17200673/AWSSample.zip)
[AWS_2.36.7-Version_success_logs.txt](https://github.com/user-attachments/files/17200678/AWS_2.36.7-Version_success_logs.txt)
[AWS_2.37.2-Version_error_logs.txt](https://github.com/user-attachments/files/17200679/AWS_2.37.2-Version_error_logs.txt)

Please let me know if you need any other informations.

**Comment by ruisebas** [comment] 2024-10-01 20:39
Hi @VijayInnovana, thanks a lot for the information.

Based on the logs, I could see that version **`2.37.2`** is generating a presigned URL pointing to a bucket in the `ap-southeast-5` region, while version **`2.36.7`** points to `ap-south-1`, which is the correct one.

I was able to reproduce the issue using the sample app you provided, and I found the root cause: You have manually implemented a mechanism to transform a `String` into the required `AWSRegionType` enum, based on hardcoding the existing region's `rawValue`s. 

Version [**2.37.0**](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.37.0) added support for the new `ap-southeast-5` region, which has "shifted" some of the internal `rawValue`s by 1, causing your custom function to become outdated. So the `Int` value that used to be associated with `ap-south-1` now is associated with `ap-southeast-5`.

We regularly add new supported regions to the SDK, so this manual approach is not recommended. 
Instead, you can just use the `NSString.aws_regionTypeValue()` function we provide:

```swift
let awsAccessRegion: NSString = "ap-south-1" // i.e. your region
let configuration = AWSServiceConfiguration(
    region: awsAccessRegion.aws_regionTypeValue(),
    credentialsProvider: credentialsProvider
)
AWSServiceManager.default().defaultServiceConfiguration = configuration
```

**Comment by VijayInnovana** [comment] 2024-10-03 06:08
Thanks for the information @ruisebas, As you suggested now my issue is resolved.

**Comment by ruisebas** [comment] 2024-10-03 14:24
Great to hear that! I'm closing this issue then.
Please let us know if you experience any other problem.

**Closed by ruisebas** 2024-10-03 14:24 UTC
Labels: question, s3, pending-maintainer-response
